### ISSUE TITLE
Vorzeitraum-Kurve im Verbrauchs-Chart ein-/ausblendbar

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#101]
Die Darstellung der Charts wird zunehmend unübersichtlicher, da der aktuelle Verbrauch des eingestellten Zeitraums wie auch der Verbrauch des Vorzeitraums dargestellt wird. Zusätzlich kommt bei Premium-Abo bei den saisonalen Zählern noch die Temperaturkurve hinzu. 
Bspw. bei Stromzähler, Stromeinspeiszähler und Stromerzeugniszähler befinden sich im Verbrauchschart 3x gestrichelte Linie mit Datenpunkten, 3x durchgezogene Linie mit Datenpunkten und Kurve für Außentemperatur. Das erschwert ein Ablesen der Werte.

Eine Lösung könnte sein, dass der Nutzer optional einstellen kann, welche Kurven im Chart angezeigt werden.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1323

**Comment by timobaehr** [comment]
https://github.com/ehwplus/ehwplus_flutter/pull/149
