### ISSUE TITLE
Kostenberechnung Warmwasser im Kostenüberblick und zwischen Ablesungen

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#102]
IST:
Im Vertrag Kaltwasser können die Kosten für Kaltwasser pro m3 eingetragen werden, im Vertrag Warmwasser die Kosten der Warmwassererhitzungskosten pro m3. In der Vertragsübersicht werden bei den WW-Gebühren die Summe aus KW-Kosten und WW-Erhitzungskosten angezeigt.
Beim Warmwasserzähler werden zwischen den Ablesungen die Kosten mit Verbrauch*(KW-Kosten + WW-Erhitzungskosten) berechnet. 
Im Kostenüberblick nur mit Verbrauch*WW-Erhitzungskosten

SOLL:
- Option im Warmwasservertrag zum Aktivieren/Deaktivieren, ob Wasser für WW vorher im Kaltwasserzähler erfasst wurde 
- Berechnung im Kostenüberblick/Zählerstände, wenn Wasser für WW nicht vorher vom Kaltwasserzähler erfasst wird: Verbrauch*(KW-Kosten + WW-Erhitzungskosten) 
- Berechnung im Kostenüberblick/Zählerstände, wenn Wasser für WW vorher vom Kaltwasserzähler erfasst wird: Verbrauch*WW-Erhitzungskosten

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1052

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1377

**Comment by timobaehr** [comment]
Wurde teilweise umgesetzt. Meines Wissens gehört Kaltwasser immer zusammen mit Warmwasser.
