### ISSUE TITLE
Abschlagsbetrag im Vertrag Fernwärme/Heizung

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#104]
Zur besseren Kostenprognose sollte die Möglichkeit bestehen bei Fernwärme/Heizung auch einen Abschlagsbetrag (wie beim Stromvertrag) einzutragen.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1316

**Comment by timobaehr** [comment]
b076135f impr(104): advance payment visible for heater
