### ISSUE TITLE
Verbrauchs-/Ertragserfassung

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#12]
Aktuell können mit der App nur Zählerstände erfasst werden. Der Verbrauch kann nur über einen Umweg mit 0-Zählerständen eingetragen werden. Deshalb möchte ich als Nutzer künftig auch den Verbrauch direkt eintragen können, ohne Umweg über die Zählerstände.

Bei folgenden Zählertypen kann auf Verbrauchs-/Ertragserfassung umgestellt werden:
- Strom
- Stromerzeugniszähler
- Ölheizung
- Kaminofen
- DSL & Telefon

Die bisherige Form von Warnungen bei der Ablesung muss überarbeitet werden bei dieser Erfassung.

In dem ConsumptionSeries sollen weiterhin Verbräuche pro Tag stehen, damit nicht die gesamte Berechnung überarbeitet werden muss.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/685

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1039

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1053

**Comment by timobaehr** [comment]
Strommessgeräte Shelly
https://support.ehwplus.com/#ticket/zoom/1241

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1451

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1466

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1564

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1621
