### ISSUE TITLE
Second Google login on web fails

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#122]
Second login fails, first works.

Error message:
```
DetailedApiRequestError(status: 401, message: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.
```

Link: https://developers.google.com/identity/sign-in/web/sign-in?hl=de

**Comment by timobaehr** [comment]
https://stackoverflow.com/questions/67502831/can-not-get-google-auth-header-after-google-signin-null-check-operator-used-on

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/855

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1419
