### ISSUE TITLE
Nutzerkonto

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#134]
Als EHW+ Nutzer, der etwas kauft, möchte ich meine Käufe auf all meinen Geräten nutzen können. Aktuell sind das Android-Phones, iPhones/iPads und auch im Browser.

Aus technischer und rechtlicher Sicht ist das leider aufwendig umzusetzen. Apple und Google erlauben es nicht, auf Käufe außerhalb des App Stores in einer App, die über das App Store installiert wurden, hinzuweisen. Aus technischer Sicht liegen bei Apple und Google unterschiedliche Kauf-Backends. Die Käufe haben also erst einmal nichts miteinander zu tun, was jedoch aufgrund der exakt gleichen Funktionalität und Darstellung für Nutzer wenig nachvollziehbar ist. Im Web ist ein Kauf aktuell überhaupt nicht möglich. Deshalb sollen Käufe künfig im EHW+ Nutzer-Konto gespeichert werden. Der Login soll via Social Login (Google, Facebook, Apple, ...) erfolgen.

## Welcher Service
- [x] Testweise aufsetzen des Service mit Zitadel
- [x] Automatisierung von Zitadel Konfiguration
- [x] ~Testweise aufsetzen des Service mit Keycloak~
- [x] ~Entscheidung für Service~ -> Decision based off of: https://areweoidcyet.com/
- [x] #172
- [x] #174
- [x] ~Wenn Social Login Google verwendet, prüfen, ob das mit dem Drive Service verknüpft werden kann~
- [x] Einbinden Sceens für Nutzerkonto nach Kauf
- [x] Aktualisierung der Datenschutzbestimmungen
- [ ] Bereitstellung dieser Version als Alpha für Testing von Janine

Out of scope:
- [x] #282

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1195

**Comment by tafaust** [comment]
-> Testweise aufsetzen des Service mit Zitadel
-> Production Setup abgeschlossen

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2042

**Comment by tafaust** [comment]
>  Wenn Social Login Google verwendet, prüfen, ob das mit dem Drive Service verknüpft werden kann

Sadly, I think that is not feasible in the scope of this story. Generally, we can try to broaden the requested scope towards google. It won't be a nice task though to distinguish between all the identity providers and storage providers (because those are naturally unrelated).

**Comment by tafaust** [comment]
This issue is basically done. Ready to be released.
