### ISSUE TITLE
Auswahl Zeitraum "an Anbieter übermittelt"

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#139]
Der Nutzer kann bereits bei Zählerständen angeben, ob er diese an den Anbieter übermittelt hat. Daraus ergeben sich Verbrauchszeiträume, welche im Kostenüberblick dargestellt werden könnten.
Der aktuelle Zeitraum sollte von zuletzt übermitteltem Zählerstand bis zum heutigen Datum gehen!

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1553

**Comment by timobaehr** [comment]
Gelöst in `1.11.46`
