### ISSUE TITLE
Alten Zählerstand übernehmen

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#14]
Als Nutzer muss ich manchmal Werte eintragen, die nervigerweise sich nicht verändert haben. Dann will ich nichts alle Ziffern tippen müssen, sondern idealerweise per Button einfach den alten Stand übernehmen können.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/663

**Comment by timobaehr** [comment]
`1.14.11`
