### ISSUE TITLE
Objektliste verschwindet hinter AppBar beim Scrollen 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#144]
IST:
Im Tab Objekt wird die Objektliste beim Scrollen in den Objekteinstellungen im Hintergrund mitgescrollt und das 1. Objekt der Liste verschwindet hinter der verkleinerten AppBar

Schritte:
1) Scrollen in Objekteinstellungen
2) Tab Objekt -> Tap auf Pfeil hinter Objektname -> Objektliste sichtbar
3) AppBar bleibt zusammengeklappt

![photo_2023-07-21 16 23 19](https://github.com/ehwplus/app-backlog/assets/13302336/606e3c89-124a-4275-b667-4949b28ddbdd)

SOLL:
Objektliste vollständig sichtbar bei verkleinerter AppBar

**Comment by timobaehr** [comment]
https://github.com/ehwplus/ehwplus_flutter/commit/b6d4f2dc7b0d2a22ea2c5ac4104cc9efb97d6371
