### ISSUE TITLE
[iOS 12] App-Absturz

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#146]
Auf iOS 12 kommt es zum Totalabsturz. Es wurde bei Google ein Bug Ticket angelegt und der Bug wurde bestätigt:
https://github.com/firebase/firebase-ios-sdk/issues/11509

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1597

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1594

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1618

**Comment by timobaehr** [comment]
This bug is caused by a bug inside Firebase iOS SDK:
https://github.com/firebase/firebase-ios-sdk/issues/11509

**Comment by timobaehr** [comment]
Das Firebase-iOS-Team kann den Fehler inzwischen reproduzieren und sucht nach einer Lösung.

**Comment by timobaehr** [comment]
Erfolgreich mit `1.10.33+681` nachgetestet:
- iOS 12.0
- iOS 12.1
- iOS 13.3
- iOS 13.4
- iOS 13.6
- iOS 14.4
- iOS 15.6
- iOS 16.2
- iOS 17.0

https://github.com/firebase/firebase-ios-sdk/issues/11509

**Comment by timobaehr** [comment]
<img width="400" alt="Bildschirmfoto 2023-10-07 um 18 12 44" src="https://github.com/ehwplus/app-backlog/assets/13302336/4a60c8e5-9e1d-486e-9deb-96cfe35bc5de">
