### ISSUE TITLE
Falscher Verbrauch nach Zählertausch und viel Zeit zw. erster und letzter Ablesung

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#150]
IST: Die App verrechnet sich beim Zählertausch. Müsste Verbrauch von 111 im Juni errechnet werden.

| Zählertausch | 
| -- | 
| ![Image](https://github.com/ehwplus/app-backlog/assets/13302336/24495b5d-7b04-4963-88e9-b202b63c8328) | 

Stellen, an denen der Verbrauch falsch ist:
- Heatmap
- Kostenüberblick
- Einzelstatistik
- Gesamtstatistik

Nachtrag:

Verbrauchsberechnung stimmt, wenn zwischen letzter Ablesung und Zählertausch (0-Zählerstand) eine kurze Zeitspanne liegt (Verbrauch dazwischen wird geschätzt):

![20230731_090934.jpg](https://github.com/ehwplus/app-backlog/assets/127824087/b4e5b543-65a7-4c32-8f40-be3851566fdb)

**Comment by janine0407** [comment]
> Hallo, ich hab da ein kleines "Problemchen". Habe seit Juni einen Zähler für das E-Auto mit einem Verbrauch von ca. 50kWh, dann einen Zählerwechsel 23.6. und dann im Juni nochmals einen Verbrauch von ca. 26 und 35kWh. In Summe ca. 110kWh im Juni. Er sagt mir aber 247,36 kWh - warum? Lg Christian


https://t.me/ehwplus/3051/8045

Erklärung: 

Hallo Christian, danke für die JSON. Sie war aufschlussreich. Wie vermutet liegt eine große Zeitspanne zwischen letzter Ablesung und dem 0-Zählerstand vor. Die App muss den Verbrauch dazwischen errechnen und nutzt dafür den errechneten Tageswert zwischen 0-Zählerstand und 1. Ablesung (42,72 kWh/Tag). Die Zeiten ohne Ablesung zwischen 20.06. um 6:56 bis 24.06. um 9:57 Uhr errechnet sie daher mit 42,72 kWh/Tag. Bei den zwei "angebrochenen" Tagen wird es anteilig berechnet. Dadurch kommt der hohe Verbrauch für Juni zustande. 

In der Regel ist die gleichmäßige Aufteilung des Verbrauchs zwischen zwei Zählerständen auf die dazwischen liegenden Tage/Stunden auch richtig. Nur beim Zählertausch führt dies zur fehlerhaften Berechnung, wenn der zeitliche Abstand zu groß ist. 

Hattest du vor dem Tausch nochmal den Zählerstand abgelesen? Du könntest einen Zählerstand für den 23.06. um 19:02 Uhr eintragen (z.B. 50,04 kWh, wenn er gleich war). Dann stimmt der Verbrauch für Juni auch wieder, weil die Zeiten vor dem Wechsel mit realem Wert (bspw. 0 kWh) berechnet werden. 
Ist das so verständlich?
