### ISSUE TITLE
Wording-Verbesserung Verbrauchs-/Ertragszähler

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#163]
## Zählerständeseite 
- Tab "Zählerstände" des Einzelzählers umbenennen in "Ablesungen"

## Zählerständeseite
- Beim Plus oben "Neue Ablesung" ändern

## In den Zählereinstellungen 
* Den Text unter Zählrichtung: "Sinkt der Wert [...]" könnte für Verbrauch/Ertrag als Erklärung erweitert werden.
* > Sinkt der Wert bei Nutzung (Füllstandsanzeige, ...) oder steigt der Wert bei Nutzung (Brennerstunden, Ölzähler, ...) oder steht jeder Ablesewert für sich (Verbrauch/Ertrag).

**Comment by timobaehr** [comment]
Duplikat von #161? Oder geht es hier um die Wording-Änderung darunter?

**Comment by timobaehr** [comment]
Gelöst in Branch `f6a8c4bc`, Version `1.10.12`, Build `655`
