### ISSUE TITLE
Toggle für Zählerstands-Chart aus Zählereinstellung für Verbrauchs-/Ertragszähler entfernen

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#164]
Da es keinen Zählerstands-Chart für Verbrauchs-/Ertragszähler gibt, kann in den Zählereinstellungen der Toggle hierfür entfernt werden.

**Comment by timobaehr** [comment]
Commit 3f52939c
Gelöst in `1.10.12`
