### ISSUE TITLE
Eigenen Service für Käufe

### ISSUE THREAD

**Issue by tafaust** [ehwplus/app-backlog#174]
- [x] Setup service to handle product purchase
- [x] Write Purchase entity
- [x] Add database
- [x] Add database schema migration
- [x] Write OpenAPI (including documentation)
- [x] Add deployment declaration
- [x] Apply deployment
- [x] Set the appropriate access rights and roles per endpoint
- [x] Add infrastructure code for IdP

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1932

**Comment by tafaust** [comment]
AC done with RBAC for now for immediate thrust. To be refactored/enhanced for multi tenancy environments. :)

**Comment by tafaust** [comment]
I close this issue. Flutter implementation will take place in #134.
