### ISSUE TITLE
keine Prognose saisonaler Zähler mit Ablesungen < 12 Monate

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#182]
Testzähler Gas. Verbrauch 100 kWh/Monat.
[Gas ab 01.12.2022.csv](https://github.com/ehwplus/app-backlog/files/12642145/Gas.ab.01.12.2022.csv)

Statistik des Einzelzählers:
Bei Ablesung unter 12 Monate = 
1) keine Restverbrauchsschätzung für den Monat, in dem die letzte Ablesung stattfand -> keine Prognose, nur IST-Wert
2) Fehlerhafte Prognose fürs Jahr -> die Prognose des betreffenden Monats wird in Jahresprognose nicht mit eingerechnet

In der Gesamtstatistik werden Verbräuche inaktiver Zähler für die Berechnung der Prognosen nicht mit berücksichtigt. Das kann auch zu obigem Fehler führen, wenn der aktive Zähler noch keine Werte aus 12 Monaten enthält. 
![2023-09-17 08 13 06](https://github.com/ehwplus/app-backlog/assets/127824087/a21a129a-8699-45e6-a0de-192bdb1be9c5)

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1852

**Comment by timobaehr** [comment]
Für 9 fehlt der Verbrauch:
```
{
11: [0.6159777777777777], 
12: [0.13946774193548392], 
1: [0.16955913978494624], 
2: [0.8282559523809524], 
3: [1.3618387096774194], 
4: [2.067115548888976], 
5: [2.540057334590671], 
6: [2.8504833218936434], 
7: [2.206867522026413], 
8: [1.9955030562473273], 
9: [], 
10: [1.4775126105203609]
}
```
