### ISSUE TITLE
Objekt-Hintergrundbild aktualisiert sich nach Objektwechsel nicht

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#188]
Hintergrundbild des Objektes aktualisiert sich erst nach Tabwechsel.

**Comment by janine0407** [comment]
> --- IS: ---
wenn ich aus der Zähleransicht das Objekt wechsele, dann wird das Objekt- Hintergrundbild nicht mit gewechselt. Das vorherige Bild bleibt, nur der Objektname ist dann mit falschem Bild zu sehen.

https://support.ehwplus.com/#ticket/zoom/2098

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2098

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2231

**Comment by timobaehr** [comment]
Fixed in 1.11.42
