### ISSUE TITLE
Typ (Wohnung/Haus) und Wohnfläche beim Durchschnittsverbrauch im Chart für Gas berücksichtigen

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#193]
similar to #19 

Typ und Wohnfläche können bereits erfasst werden. Im Verbrauchstext wird auch bereits die Wohnfläche herangezogen und der kWh-Verbrauch bezieht sich, falls angegeben auf die Wohnfläche.

Der Durchschnittsverbrauch bei Gas im Chart bezieht sich aktuell nur auf die Anzahl der Personen im Haushalt. 
Ähnlich dem Verbrauchstext, soll auch im Chart der Durchschnittsverbrauch anhand Typ und Wohnfläche angezeigt werden.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1855

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2093

**Comment by timobaehr** [comment]
Duplikat von #19.
