### ISSUE TITLE
In Heatmap die Anzeige der Jahre einstellbar machen

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#196]
Bei Daten aus vielen Jahren/Jahrzehnten ist die Heatmap-Liste sehr lang und somit unübersichtlich. 
Die Anzeige der Jahre sollte verkürzbar/einstellbar sein. Mithilfe Dropdown zB "Alle Daten", "Letzte 10 Jahre" etc. 

Darstellung:
![photo_2023-10-01 11 41 43](https://github.com/ehwplus/app-backlog/assets/13302336/26ea031a-ec37-45aa-a0ba-58949218ede3)

**Comment by janine0407** [comment]
> Bei meinem Datenbestand [seit 1996; Anm. d. Verf.] habe ich dann allerdings Anzeigen wie in Screenshot_3, was nicht hilfreich ist.
> Diese riesige Anzeige sollte verkürzbar sein. Z.B. "Alle Daten" und "10 Jahre" würde sicher reichen.
> Ich hab das mal versucht in Screenshot_4 darzustellen, wie ich das für möglich halten würde.

https://support.ehwplus.com/#ticket/zoom/1855

**Comment by timobaehr** [comment]
`fl_heatmap` Package wurde um Einblenden-Funktionalität erweitert.

Version 0.4.0
https://pub.dev/packages/fl_heatmap
