### ISSUE TITLE
Chart mit mehreren Zählertypen mit Darstellungsfehlern

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#199]
## Das Gruselkabinett

Vermutung: Der Fehler scheint nur bei Charts mit mehreren Typen aufzutauchen. Werden die Charts der einzelnen Zähler geöffnet, kommt es nicht zu Darstellungsfehlern.

Beim Datenbeispiel GeorgHerbert8 liegt es an einer falschen Index-Bildung für den Vorzeitraumchart.

![Image](https://github.com/ehwplus/app-backlog/assets/13302336/b25ac004-935e-4df1-bdec-c18642d6b92f)

![384188279_824342926037811_4655201777066466151_n](https://github.com/ehwplus/app-backlog/assets/13302336/f1f5047a-535d-40d0-9928-76cc14e8ec8f)

![photo_2023-10-01 11 38 10](https://github.com/ehwplus/app-backlog/assets/13302336/0e453576-9aac-4398-a315-0ee46398bb03)

![383083158_6934626889934209_3321924094783248309_n](https://github.com/ehwplus/app-backlog/assets/13302336/79a088f5-ec97-42b5-985e-2db31b5db10b)

**Comment by timobaehr** [comment]
https://business.facebook.com/latest/inbox/all?asset_id=105819178429429

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/8901

**Comment by timobaehr** [comment]
Die Wochenwerte dürfen nicht um einzelne Tage variieren, benötigt wird z.B. immer Montag.
<img width="388" alt="Bildschirmfoto 2023-10-03 um 22 16 53" src="https://github.com/ehwplus/app-backlog/assets/13302336/b6734fa3-50b7-4608-a1ea-6d7c02b14af2">

**Comment by timobaehr** [comment]
Erster Bug: Wenn die erste Ablesung z.B. an einem Dienstag war, dann sollte der Datenpunkt trotzdem auf den Montag vor der Ablesung zeigen. Im Chart erscheint dann anstelle `2.10. - 8.10.` nun `1.10. - 8.10.`, auch wenn die erste Ablesung am 2.10. war. Das ist jedoch nur nötig, wenn es mehr als einen Zählertyp gibt. Gibt es nur einen Zählertyp im Chart, wird es nicht gemacht.

Zweiter Bug: Die Länge des Vorzeitraums kann für unterschiedliche Zählertypen unterschiedlich sein und das muss dann bei der Index-Bildung berücksichtigt werden.
