### ISSUE TITLE
Virtueller Zähler

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#2]
Als Nutzer möchte ich mehrere Zähler miteinander verrechnen können, weil das Ergebnis von Addition/Subtraktion mir bei der Einschätzung meines Verbrauchs/Ertrags hilft.

## Offene Bugs

- [ ] Die Kostenberechnung des virtuellen Zählers ist aus meiner Sicht falsch. Bei dem Verbrauchswert ergäbe sich ein Preis von 68 ct/kWh (s. auch Anlage). Ich habe dem Stromeinspeisezähler bis Juli Preise von 46 ct/kWh und ab 1.7. 38 ct/kWh zugeordnet. Die gleichen Preise hätte auch der Stromzähler. Dem Stromerzeugniszähler kann ja kein Vertrag mit Preisen zugeordnet werden. Wie die angegebenen Kosten berechnet werden, kann ich daher leider nicht ableiten.

## Gelöste Bugs

- [x] Verbrauch virtueller Zähler wird in Gesamtstatistik hinzugerechnet
- [x] Wurde ein im virtuellen Zähler verlinkter Unterzähler deaktiviert und ein neuer Unterzähler verlinkt, dann werden für alle Zähler auch nach Neustart der App keine Statistiken mehr angezeigt. (unabhängig, ob verknüpft mit virtuellem oder nicht)
_Bei Deaktivierung des Hauptzählers und Verlinkung mit neuem Hauptzähler, tritt das Problem nicht auf._
- [x] Unterzähler können nicht ausgewählt werden
- [x] Es kann kein Hauptzähler ausgewählt werden, wenn der verknüpfte Raum gelöscht wurde, stattdessen ein grauer Bildschirm

## "Einstellungen" eines virtuellen Zählers

Gesamte Einstellungen | Initialer Zählerstand | Nur Hauptzähler ausgewählt
-------- | -------- | --------  
<img width="265" alt="Bildschirmfoto 2023-10-21 um 20 15 23" src="https://github.com/ehwplus/app-backlog/assets/13302336/d4f9c6c3-255a-4375-9aad-4342d04193d9"> | ![photo_2023-10-21 20 27 44](https://github.com/ehwplus/app-backlog/assets/13302336/0d1925f2-0ae9-433b-827c-1a2d59ad657a)  | <img width="562" alt="Bildschirmfoto 2023-10-21 um 20 23 52" src="https://github.com/ehwplus/app-backlog/assets/13302336/9a67792a-a30c-4959-b3b3-0c3aaafeebbc">

- [x] Virtueller Zähler kann als Typ ausgewählt werden
- [x] Im initalen Zustand wird ein Button angezeigt, mit dem der Hauptzähler ausgewählt werden kann. Die Einstellung wird persistiert. 
- [x] Im initalen Zustand können keine abzuziehenden / zu addierenden Zähler ausgewählt werden.
- [x] Wird der Hauptzähler entfernt, werden auch alle bzuziehenden / zu addierenden Zähler entfernt. Die Einstellung wird persistiert. 
- [x] Nach Auswahl des Hauptzählers erscheint der ausgewählte Hauptzähler im Abschnitt Hauptzähler.
- [x] Nach Aaswahl des Hauptzählers können abzuziehenden / zu addierenden Zähler hinzugefügt werden. Die Einstellung wird persistiert. 
- [x] Abzuziehende / zu addierende Zähler können wieder entknüpft / gelöscht werden. Die Einstellung wird persistiert. 

### Umgang mit Zählertausch des Hauptzählers
- [x] Wenn ein Zähler auf inaktiv gesetzt wird, muss künftig im alten Zähler der neue Zähler verlinkt werden.
![photo_2023-10-29 08 38 44](https://github.com/ehwplus/app-backlog/assets/13302336/ce2afe00-c2bf-4bca-9b95-8e1612623383)
- [x] Bei der Berechnung verlinkt der alte Zähler stets auf den neuen. Es müssen alle aus der Reihe berücksichtigt werden.
- [x] In den Zählereinstellungen soll stets der aktuellste Zähler aus der Reihe erscheinen, also derjenige ohne Referenz auf einen Zähler.

### Andere Edge Cases / noch zu testen
- [x] Wird ein Zähler gelöscht, dann steht im virtuellen Zähler zunächst noch die Referenz auf den gelöschten Zähler drin. Falls nötig, sollte sie entfernt werden.
- [x] Wenn der virtuelle Zähler frisch konfiguriert wurde, sollte die Berechnung angestoßen werden.

### Welche Zähler kommen als Hauptzähler in Frage?
- [x] Zunächst nur bestimmte Typen zunächst (Stromzähler, Kaltwasserzähler).

### Abhängig vom Hauptzähler, welche Zähler können anschließend verrechnet werden?
Abhängig vom Zählertyp des Hauptzählers:
* [x] Wurde Kaltwasser ausgewählt, dann alle anderen Kaltwasserzähler
* [x] Wurde Strom ausgewählt, dann alle anderen Stromzähler, Wärmpepumpe, Einspeiszähler (nur bei Abzug), Erzeugniszähler (nur bei Addition)

### Kosten
- [x] Der virtuelle Zähler hat keine eigenen Kosten. Die Kosten/Erträge ergeben sich aus der Summe der addierten/subtrahierten Zähler.

### Statistiken
- [x] Der Zählerstände-Chart soll nie angezeigt werden
- [x] Ist der virtuelle Zähler unvollständig konfiguriert, soll eine Fehlermeldung anstelle der Statistiken erscheinen.
![photo_2023-11-04 14 53 38](https://github.com/ehwplus/app-backlog/assets/13302336/1b305bdc-d164-4518-89c5-d351b162972f)

### Feature-Umfrage
- [x] Nutzer, die sich das Feature gewünscht haben, sollten einen Hinweis erhalten, dass das Feature umgesetzt wurde. 

## Anwendungsfälle

Der virtuelle Zähler ist ein besonderer Zähler. Er verrechnet "reguläre Zähler" miteinander.

1.) **Kaskadenschaltung** So haben manche Häuser einen Hauptzähler und einen Zähler für die Wärmepumpe. Der Haushaltsstrom ergibt sich erst durch die Differenz, also Hauptzähler - Wärmepumpenzähler. Das wird auch als Kaskadenschaltung bezeichnet.
`Hauptzähler (Bezogener Strom)` - `Wärmepumpenzähler`  = `Haushaltsstrom`

2.) **Virtueller Wasserzähler:** Manchmal sparen sich Vermieter im eigenen Haus auch einen Zähler. Aus Hauptwasserzähler und einem weiteren Wasserzähler entsteht die Differenz für die zweite Wohnung.
`Hauptwasserzähler` - `Wasserzähler 1`

3.) **E-Auto:** Wird das Elektroauto geladen mit dem regulären Strom, dann wird das meist über einen separaten Zähler erfasst. Wie bei der Wärmepumpe entsteht durch die Differenz von Hauptzähler und E-Ladeeinheit der Haushaltsstrom.
`Hauptzähler (Bezogener Strom)` - `Wallbox/Ladeeinheit` = `Haushaltsstrom`

4.) **Haushaltsstrom mit PV:** Bei einer PV-Anlage kann ein virtueller Zähler den Eigenverbrauch darstellen:
`Hauptzähler (Bezogener Strom)` + `Erzeugter Strom` - `Eingespeister Strom` = `Haushaltsstrom`
Der Haushaltsstrom bildet auch die Grundlage für den Autarkiegrad:
`1` - (`Hauptzähler (Bezogener Strom)` / `Haushaltsstrom`) = `Autarkiegrad`
Wenn ein E-Auto geladen wird und eine PV-Anlage vorhanden, dann:
`Hauptzähler (Bezogener Strom)` + `Erzeugter Strom` - `Eingespeister Strom` - `Wallbox/Ladeeinheit` = `Haushaltsstrom`

## Monetarisierung
- [x] Der virtuelle Zähler ist nicht kostenlos, man benötigt entweder das Abo oder irgendeinen EInzelkauf.

## Wünsche von Nutzern

Carsten am 13.12.:
> Ich würde mich über das hinzufügen von virtuellen Zählern freuen. z.b. für die Berechnung des Eigenverbrauchs der WP bei Kaskadenschaltung oder des Gesamtverbrauches wäre diese Funktion sehr hilfreich.

Mario am 23.12.:
> Kann man in der App einen virtuellen Zähler erstellen? Also Hauptzähler - Unterzähler= Nebenwohnung?

Daniel am 23.12.:
> Kann man einen Differenzzähler einrichten also z.b hauptzähler-wärmepumpenzähler?

Christian am 25.03:
> Ich habe für mein E Auto einen separaten Zähler, der aber hinter meinem Hauptzähler für Strom hängt.  Ein virtueller Zähler, der aus der Differenz damit den nur im Haushalt verbrauchten Strom ermittelt, wäre für die einfache Übersicht sehr hilfreich.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/722

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/404

**Comment by timobaehr** [comment]
1) Dieser Fall stimmt so nur in Kombination mit einer PV-Anlage und Einspeisung. Ohne PV arbeiten die Zähler separat.
2) Das ist der eine Andwendungsfall für Wasser. Wir haben z.b. noch einen Aussenwasserzähler für den wir kein Abwasser bezahlen. Hier bildet die Differenz aus Hauptzähler und Aussenzähler den Hausverbrauch für den Abwasser bezahlt werden muss.
3) Siehe Hinweis 1)
4) Zusätzlich gilt bei der Kaskadenschaltung das gleiche auch bei der Einspeisung. Der Eigenverbrauch der Wärmepumpe lässt sich nur aus der Differenz von Hauptzähler (WP) und Hauszähler berechnen.
5) Ein virtueller Zähler könnte auch für den Gesamtverbrauch des Hauses verwendet werden, in dem Falle die Summe aus Hausstrom und PV Eigenverbrauch laut Smartmeter oder nach Ablesung der PV Anlage.
6) Ein weiterer Anwendungsfall ist der Gesamtverbrauch bei HT/NT Zählern, die ja aktuell als 2 verschiedene Zähler geführt werden müssen. (Finde ich übrigens etwas umständlich :)).
Für die Umsetzung:
Ich finde die Umsetzung bei HB-Verbrauchszähler ganz gut. Hier kann man einfach Zähler und Operatoren auswählen. Hab mal 2 Screenshots in den Anhang gepackt.
Was nett wäre, aber vielleicht schwerer umzusetzen, sind Statistiken für die virtuellen Zähler.

https://support.ehwplus.com/#ticket/zoom/287

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/715

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/928

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1105

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1135

**Comment by timobaehr** [comment]
> Haus mit zwei Haushalten, allerdings Strom mit Subzähler. Der Hauptzähler misst Gesamtstrom, ist es möglich dass diese App den Substrom vom Gesamtstrom abzieht und dadurch für jede Wohnung den Verbrauch richtig ausgibt?
z.B. Zähler x ist Sub von Zähler y

https://support.ehwplus.com/#ticket/zoom/1156

**Comment by timobaehr** [comment]
> Es wäre toll, wenn mal die Möglichkeit hätte die verschiedenen Zähler zu addieren und zu subtrahieren ab einem bestimmten Datum. Also wenn mal 3 Zähler hat kann man angeben welche Zählerstände ab einem bestimmten Datum addiert und oder von einander subtrahiert werden.

https://support.ehwplus.com/#ticket/zoom/1173

**Comment by timobaehr** [comment]
> Ich wohne in einem ZFH. Dieses hat einen Hauptzähler und einen weiteren Zähler für die EG-Whg..
> Meinen Wert ermittle ich also wie folgt:
> Zählerstand vom Hauptzähler minus Zählerstand vom zweiten Zähler (EG).

https://support.ehwplus.com/#ticket/zoom/1199

**Comment by timobaehr** [comment]
> Bei uns ist eine Wallbox am normalen Stromzähler angeschlossen. Über den integrierten Zähler des Wallbox, weiß ich, wie viel über die Wallbox geladen wird. Ist es möglich, diese Werte irgendwie vom Hausstromzähler abzuziehen, sodass nur der Verbrauch ohne Wallbox errechnet wird.
> Beispiel: Ich lese ein Mal in der Woche den Zählerstand ab und gebe gleichzeitig ein, wie viel ich über die Wallbox geladen habe bzw. somit "abziehen" möchte. 

https://support.ehwplus.com/#ticket/zoom/1296

**Comment by timobaehr** [comment]
> Es wäre toll, hier innerhalb der App eine möglichkeit für die flexible Erstellung von Zählern zu erhalten wie z.B. Betriebsstundenzähler oder ähnliches.

https://support.ehwplus.com/#ticket/zoom/1445

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1440

**Comment by timobaehr** [comment]
> Ich würde gerne etwas genauer erfassen können, wie hoch der Anteil des E-Autos am Gesamtstromvebrauch ist. 

https://support.ehwplus.com/#ticket/zoom/1437

**Comment by timobaehr** [comment]
> Oft gibt es einen Gesamtzähler für das Haus und Unterzähler für Teilbereiche. Wie sich der Differenzbereich entwickelt bleibt dann unerkannt.
> hz- uz1 -uz2 = vz

https://support.ehwplus.com/#ticket/zoom/1422

**Comment by Rama-Drama** [comment]
Ich bin auch voll dafür, so kann man das Messkonzept 8 darstellen.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1611

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1593

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1621

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1633

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1773

> Bei dem Messkonzept 2u ist es so:
>
> Der Strom für die Wärmepumpe und der Verbrauchsstrom fließen durch Z2 (WP und Verbrauchsstrom werden dort gezählt).
> Der Strom für die WP fließt weiter zur WP. Ende.
> Der Verbrauchsstrom fließt weiter durch Z1 (Haus wird dort noch einmal gezählt).
> 
> Z2 zählt also den Strom für die WP und den Verbrauchsstrom
> Z1 zählt nur den Verbrauchsstrom.
> Der Verbrauchsstrom wird somit doppelt (Z2 & Z1) gezählt.
> 
> Will man den Verbrauchsstrom wissen, kann man einfach Z1 ablesen.
> Will man den Strom für die WP wissen, muss man Z2 - Z1 rechnen.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1821

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1889

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/194

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1991

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2023

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2027

**Comment by timobaehr** [comment]
Löst Feature-Vorschlag `Elektroauto laden und Haushaltsstromverbrauch rausrechnen`/`wallbox-strom-abzugszaehler `:
_Wird ein Elektroauto geladen und wird der Stromverbrauch dafür durch einen Zähler erfasst, so sollte der Reststromverbrauch für den Haushaltsstrom herausgerechnet und visualisiert werden können, damit der Haushaltsstromverbrauch besser eingeschätzt werden kann._

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2063
