### ISSUE TITLE
[Kostenüberblick] Aktuelle Erträge sollten nicht in Intervallen der Vergangenheit erscheinen

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#206]
Die App zeigt im Kostenüberblick für Jahre/Monate/Wochen Erträge für die Vorjahre an, obwohl dort noch gar nichts erzeugt wurde.

Angezeigt werden Erträge für den Einspeiszähler und den Erzeugniszähler.

![Image](https://github.com/ehwplus/app-backlog/assets/13302336/214789e8-c035-45b8-978b-1cefb166a64b)

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1952

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1974

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1983

**Comment by timobaehr** [comment]
Gefixt: https://github.com/ehwplus/ehwplus_flutter/pull/148/files
