### ISSUE TITLE
keine Statistikanzeige für Warmwasser in Gesamtstatistik (Tab Statistiken)

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#207]
IST:
nur Warmwasserzähler, kein Kaltwasserzähler
-> keine Statistikanzeige (grauer Kasten, graue Seite) im Tab Statistiken
iPhone & Android-Smartphone: ganzer Bildschirm grau
iPad und Mac: nur Statistik für Wasser grau

Mac:
<img width="1237" alt="Bildschirmfoto 2023-10-10 um 17 47 10" src="https://github.com/ehwplus/app-backlog/assets/127824087/8ed49372-b31d-49d5-9e7b-ff903a6c7702">

Android-Smartphone:
![Bug 2023-10-10 17 57 48](https://github.com/ehwplus/app-backlog/assets/127824087/facdfdc4-a4e6-4cf6-9d08-e0124c9bb360)

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/8993

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1963

**Comment by timobaehr** [comment]
e47e8fa5 fix(207): No cold water counter created, show stats
