### ISSUE TITLE
Optimierung der Zeitanzeige letzte Ablesung in Zähler-Karte 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#209]
Die Anzeige in der Zählerkarte wann die letzte Ablesung stattgefunden hat, ist aktuell von der Uhrzeit abhängig. Fand die letzte Ablesung z.B. am 01.10.2023 um 20:00 Uhr statt und jetzt ist 19:59, so steht im Zeitraum 
02.10.2023 um 00:00 Uhr bis 02.10.2023 um 23:59 Uhr = "zuletzt gestern", 
03.10.2023 um 00:00 Uhr bis 03.10.2023 um 19:59 Uhr = "zuletzt vor einem Tag"
03.10.2023 um 20:00 Uhr bis 04.10.2023 um 19:59 Uhr = "zuletzt vor 2 Tagen" usw. da. 

Über den Monats-/Jahreswechsel erscheint folgende Anzeige (letzte Ablesung 31.10.2023 um 20:00 Uhr):
01.11.2023 um 20:00 Uhr bis 02.11.2023 um 19:59 Uhr = "zuletzt vor einem Tag"

**Optimierung:** 
Die Anzeige der letzten Ablesung in der Zählerkarte kann verbessert werden, indem für den Tag der Ablesung die Zeit bis 0:00 Uhr in "zuletzt vor x Minuten/Stunden" angezeigt wird und ab dem Folgetag der neue Tag immer ab 0:00 Uhr beginnt. Dann sollte die Anzeige "zuletzt gestern" und "zuletzt vor x Tagen/Monaten" erscheinen. 
1. Beispiel mit neuer Anzeige: 
01.10.2023 bis 23:59 Uhr = zuletzt vor x Minuten/Stunden
02.10.2023 um 0:00 Uhr bis 23:59 Uhr = zuletzt gestern
03.10.2023 um 0:00 Uhr bis 23:59 Uhr = zuletzt vor 2 Tagen usw

2. Beispiel mit neuer Anzeige: 
31.10.2023 bis 23:59 Uhr = zuletzt vor x Minuten/Stunden
01.11.2023 um 0:00 Uhr bis 23:59 Uhr = zuletzt gestern
02.10.2023 um 0:00 Uhr bis 23:59 Uhr = zuletzt vor 2 Tagen usw.

**Comment by janine0407** [comment]
> [...]ich habe Ihnen heute Vormittag geschrieben und die Uhrzeit war früher als die am 01.10. Also noch keine kompletten 11 Tage. Kommt man nicht gleich drauf. Vielleicht sollte aber ab 0:00 Uhr doch schon der neue Tag gerechnet werden?

https://support.ehwplus.com/#ticket/zoom/1981

**Comment by janine0407** [comment]
evtl. zusammen mit #98

**Comment by timobaehr** [comment]
2289302a
