### ISSUE TITLE
Überschrift in Vertrag Heizung/Fernwärme doppelt 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#237]
Betroffene Zählertypen: Heizkörper/Fernwärme

![Screenshot_20231116_062553.jpg](https://github.com/ehwplus/app-backlog/assets/127824087/591799fb-5d09-4061-aa68-a97776872bc7)

**Comment by timobaehr** [comment]
Fixed in Commit 489df9de
