### ISSUE TITLE
Strom-/Gaspreisbremse

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#24]
# Preisbremsen

Für einen Verbrauch bis X kWh fällt ein geringerer Preis pro kWh an.

## Design

| Deutschland | Österreich |
|--|--|
| ![Screenshot_1677964400](https://user-images.githubusercontent.com/13302336/222928949-e8febdf0-f5ed-4933-994d-6684d4029c8c.png) | ![Screenshot_1677962752](https://user-images.githubusercontent.com/13302336/222928019-82db53cc-1859-44d3-9ed9-86805d6e52ed.png) |

#
# Strompreisbremse

Österreich und Deutschland haben eine Strompreisbremse eingeführt.

### Deutschland

Die Strompreisbremse basiert auf dem Vorjahresverbrauch 2021, den der Stromanbieter ermittelt. Für 80% der Verbrauchs 2021 (oder der vom Netzbetreiber prognostizierte Verbrauch) ist der Preis bei 40 Cent pro kWh gedeckelt.  Die Preisbremse greift ab März 2023, allerdings rückwirkend ab Januar, und endet am 30. April 2024. Für die Monate Januar 2024 bis April 2024 scheint ein anteiliger Verbrauch (4 Monate von 12) relevant zu sein.

### Österreich

Jeder Haushalt erhält 2900 kW unabhängig von der Anzahl der darin lebenden Personen für 10 Cent (wenn der Preis kleiner 40 Cent), bei höherem Preis werden maximal 30 Cent abgezogen. Würde ein Anbieter 45 Cent verlangen, würden die ersten 2.900 kWh 15 Cent kosten. Die Preisbremse greift ab 1. Dezember 2022 und gilt bis einschließlich 30. Juni 2024.

### Deutschland

Die Gaspreisbremse verbilligt den Gaspreis auf 12 Cent pro Kilowattstunde. Heizt Du per Fernwärme, setzt die Preisbremse schon bei 9,5 Cent an. Die vergünstigten Preise gelten nur für 80 Prozent des Vorjahresverbrauchs. Die Preisbremse greift ab März 2023.

### Österreich

Eine Gaspreisbremse wurde nicht verabschiedet. In Österreich heizen 25% der Haushalte mit Erdgas.

**Comment by Haseruli** [comment]
danke für die Annahme des Vorschlages

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/373

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/460

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/774

**Comment by timobaehr** [comment]
Was ist mit Entlastungsbeträgen für Januar und Februar 2023 gemeint?

In DE gilt sie vom 1. März 2023 bis 30. April 2024. Sie gilt also für 14 Monate. Gegeben sei der Vorjahresverbrauch von 80%, sagen wir der Stromverbrauch 2022 lag bei 1200 kWh, also 960 kWh. Was ist mit den letzten zwei Monaten in 2024, also März und April 24.? Wird die Grenze dann auf zwei Monate heruntergerechnet, also 160 kWh?

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1119

**Comment by benzman81** [comment]
@timobaehr In den FAQs ist das recht gut erklärt, finde ich. Die Differenz zwischen dem Preis des Strom-/Gasanbieters und der Strom-/Gaspreisbremse wird als Entlastungsbeitrag beim Versorger dem Kunden gutgeschrieben. Da das ja Rückwirkend zum 1.1. gilt, wird somit im März der dreifache Entlastungsbeitrag gutgeschrieben.
Für 2024 müsste das anteilig gerechnet werden.

Strom: https://www.bmwk.de/Redaktion/DE/Downloads/F/faq-strompreisbremse.pdf?__blob=publicationFile&v=4

Gas: https://www.bmwk.de/Redaktion/DE/Downloads/F/faq-gaspreisbremse.pdf?__blob=publicationFile&v=10

**Comment by timobaehr** [comment]
Also mein Strompreis kostet 44 Cent, ich verbrauche weniger als 80% des Vorzeitraums, sagen wir ich verbrauche jetzt 64%, dann wird mir für 16% eine Reduzierung des Strompreises um 44 Cent pro kWh gewährt? Und für die anderen 64% bezahle ich dann 40 Cent. Oder was meinen die mit "Entlastung in voller Höhe"?

**Comment by benzman81** [comment]
Wenn du in 2023 80% oder weniger verbrauchst als im jahr 2022, dann zahlst du für jede kw ja eh nur 40c. Zusätzlich bekommst du noch eine “belohnung“ für alles was du über die 80% mehr sparst. Für jedes kw unter den 80% bekommst du den Preis, denn dein aktualler anbieter verlangt, erstattet. Hast du in 2022 10.000 kw verbaucht und in 2023 nur 7.000, dann zahlt du 7.000 x 40c = 2.800€ minus die Belohnung für das gesparte 1.000 x 44c = 440€. Bedeutet man zahlt dann nur noch 2.800€ - 440€ = 2.360€.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1163

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1119
