### ISSUE TITLE
keine Prognose saisonaler Zähler bei fehlendem abgeschlossenem Monat

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#248]
IST:
- Fehlende Prognose bei saisonalen Zählern, wenn Daten von weniger als einem vollständig abgeschlossenem Monat (< 27 Tage) vorhanden sind 
- es wird nur tatsächlicher Verbrauch im Kostenüberblick angezeigt

SOLL:
Prognose, auch wenn es noch keinen abgeschlossenen Monat gibt (wie bei nicht-saisonalen Zählern)

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2146

JSON mit Verbrauchsdaten vom 26.10.23 bis 24.11.23 im Ticket

**Comment by timobaehr** [comment]
Fixed in 1.11.24
