### ISSUE TITLE
Fehlerhafte Berechnung im Kostenüberblick virtueller Zähler bei Eintragung Grundgebühr

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#250]
### Gegeben:
- Stromzähler Gesamt 
- Stromzähler Hinterhaus 
- Stromvertrag X mit Arbeitspreis und Grundgebühr (beiden Stromzählern zugeordnet)
- virtueller Zähler "Stromzähler Vorderhaus": Hauptzähler: Stromzähler Gesamt; abzuziehender Zähler: Stromzähler Hinterhaus

## IST: 
Im Kostenüberblick des virtuellen Zählers werden die Gesamtkosten falsch berechnet und die Grundgebühr steht als negativer Betrag da. 

Anzeige im Kostenüberblick jährliche Statistik 2023:

|  | Verbrauchskosten (linker Kreis) | Grundgebühr | Gesamtkosten (neben Balken) |
| --- | --- | --- | --- |
| Stromzähler Gesamt | 1.876,11 € | 121,89 € | 1.998,00 € | 
| Stromzähler Hinterhaus | 505,24 € | 121,89 € | 627,13 € |
| virtueller Zähler | 1.370,87 € | - 121,89 € | 1.248,98 € |
 

## SOLL:

erwartete Anzeige im virt. Zähler:

|  | Verbrauchskosten (linker Kreis) | Grundgebühr | Gesamtkosten (neben Balken) |
| --- | --- | --- | --- |
| virtueller Zähler | 1.370,87 €  | 0,00 € | 1.370,87 € | 

Richtige Berechnung erfolgt zB, wenn es zwei separate Verträge zu jedem Zähler gibt! Ist der selbe Vertrag für Hauptzähler und Unterzähler ausgewählt, stimmt die Berechnung nicht mehr.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/375

bereinigte JSON-Datei mit relevanten Daten im Ticket

**Comment by timobaehr** [comment]
```dart
    /// Given two electricity meters with two different contracts, the base
    /// price of both contracts must be added. However, if it is the same
    /// contract, the base price should only be taken into account once when
    /// adding two series. An example of this would be two heating meters, but
    /// with the same contract at the end.
    final bool sumUpBasePrice = mergedContractsInUse.length != contractsUsed.length;
```
Dieser Code in `consumption_series.dart` funktioniert wie erwartet.

Aber es muss wohl unterschieden werden. Bei Stromzählern/Gaszählern fällt die Gebühr pro Zähler an. Bei Wasserzählern oder Heizkörperzählern fällt sie aber nur einmal an.
