### ISSUE TITLE
Weißer Screen bei neu angelegtem Zähler 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#257]
## IST: 
Weißer Screen mit orangen Button erscheint bei Tap auf neu angelegtem Zähler 

![Screenshot_20231129_141753.jpg](https://github.com/ehwplus/app-backlog/assets/127824087/e2d15d40-a1bf-40d0-9936-3eec02b7e6d0)

Schritte:
1. Neuen Zähler anlegen (zB Stromzähler)
2. Nach Anlage in Zählerliste den neuen Zähler auswählen 

## SOLL

Screen mit Hintergrundbild Zähler und Hinweis mit Eintragung eines Zählerstandes

**Comment by timobaehr** [comment]
![photo_2023-12-03 09 33 27](https://github.com/ehwplus/app-backlog/assets/13302336/c0ceb35c-c9a8-40fa-85bf-27d8c4f61462)
