### ISSUE TITLE
Objekt erscheint doppelt in der Objekte-Liste

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#26]
IST:
Das Objekt erscheint doppelt in der Liste, aber ein anderes verschwindet.
![photo_2023-01-24 20 48 35](https://user-images.githubusercontent.com/13302336/214394316-0c914a2f-1af4-4af3-8d2f-ffae854d0b08.jpeg)

SOLL:
Objekte dürfen nur einmal in der Liste von Objekten erscheinen

SCHRITTE ZUM REPRODUZIEREN:
1. ...
2. ...

**Comment by timobaehr** [comment]
Eventuell korrigiert mit Version 1.7.17

**Comment by EHWPlusSupport** [comment]
Trotz mehrerer Versuche konnte ich das Problem nicht reproduzieren
