### ISSUE TITLE
Bei Verträgen ohne Startzeitpunkt, aber mit altem Vertrag mit Enddatum, Vertragsstart annehmen

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#262]
## IST: 
Im Ablesechart werden nicht die Ablesungen der aktuellen Vertragslaufzeit angezeigt, wenn der neue/aktuelle Vertrag kein Startdatum/nur Enddatum hat und es einen älteren Vertrag mit Start- und Enddatum gibt. 

Schritte zur Reproduktion:
1) Zähler anlegen
2) Ablesungen eintragen, bspw. für 01.01.2023, 01.05.2023, 01.07.2023, 06.10.2023 und 10.12.2023
3) Vertrag 1 anlegen: 01.11.2022 bis 01.07.2023
4) Vertrag 2 anlegen: kein Startdatum; Enddatum: 31.08.2024
5) Ablesechart "Vertragslaufzeit" auswählen
6) Chart zeigt Ablesungen 01.01.2023, 01.05.2023 und 01.07.2023 an, erwartet: 06.10.2023 und 10.12.2023

Testobjekt: 
[Objekt mit Testdaten.json](https://github.com/ehwplus/app-backlog/files/13628470/Another.object_2023-12-10_0502.json)

 
## SOLL:
Die Ablesungen der aktuellen Vertragslaufzeit sollen im Chart angezeigt werden. 
Dafür muss vmtl. beim aktuellen Vertrag das Startdatum intern errechnet werden.

**Comment by timobaehr** [comment]
Gelöst in `1.11.38`
