### ISSUE TITLE
Einzelstatistik wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#272]
## IST:

Im Tab Einzelstatistik sind die Statistiken nach rechts verschoben und abgeschnitten, Kostenüberblick wird nicht vollständig angezeigt, Scrollen nicht möglich. 

![2023-12-24 13 49 49](https://github.com/ehwplus/app-backlog/assets/127824087/848168a4-6bb2-4b46-9f06-caaf982f6aea)

Fehler tritt unter folgenden Voraussetzungen auf: 
- mind. 2 Zähler (einer aktiv, einer inaktiv) mit Zählerständen
- aktiver Zähler: Erstablesung = 0-Wert
- Verträge: mind. ein Altvertrag mit Start- und Enddatum und ein aktueller Vertrag ohne Startdatum/nur Enddatum
- in Einzelstatistik beim Chart ist "Vertragslaufzeit" ausgewählt 

bereinigtes Objekt zum Testen: 
[Haus_2023-12-24_0143.json](https://github.com/ehwplus/app-backlog/files/13761886/Haus_2023-12-24_0143.json)

## SOLL:
Einzelstatistik des aktuellen Zählers soll wieder richtig angezeigt werden

## Stacktrace

```
[log] [error] [2023-12-27 09:33:53] BaseChartState | Billing period is not available because no contract ranges are given, falling back to last 12 months.
>> Stacktrace >> 
2      BaseChartState.range.<anonymous closure> (package:energy_tracker/chart/time_series_line_chart/base_chart_state.dart:103:15)
#3      BaseChartState.range (package:energy_tracker/chart/time_series_line_chart/base_chart_state.dart:139:27)
#4      _ConsumptionChartState.setCurves (package:energy_tracker/chart/time_series_line_chart/consumption_chart.dart:313:9)
#5      _ConsumptionChartState.build (package:energy_tracker/chart/time_series_line_chart/consumption_chart.dart:112:7)
```

**Bug könnte mit #262 zusammenhängen**

**Comment by timobaehr** [comment]
Gelöst in `1.11.38`.
