### ISSUE TITLE
Chart Ablesungen mit Auswahl "Vertragslaufzeit" unvollständig

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#273]
## IST:

Im Chart Ablesungen wird im aktiven Zähler nur der Zählerstand der Erstablesung und weitere eingetragene Zählerstände werden nicht angezeigt.

![2023-12-24 14 29 16](https://github.com/ehwplus/app-backlog/assets/127824087/d1dbaad4-197d-4f3e-bd8a-71db787f5be4)

Fehler tritt unter folgenden Voraussetzungen auf:

- mind. 2 Zähler (einer aktiv, einer inaktiv) mit Zählerständen
- aktiver Zähler: Erstablesung Wert > 0
- Verträge: mind. ein Altvertrag mit Start- und Enddatum und ein aktueller Vertrag ohne Startdatum/nur Enddatum
- in Einzelstatistik beim Chart ist "Vertragslaufzeit" ausgewählt

bereinigtes Objekt zum Testen: [Haus_2023-12-24_0225.json](https://github.com/ehwplus/app-backlog/files/13761948/Haus_2023-12-24_0225.json)

## SOLL:

Im Ablesechart sollen alle erfassten Zählerstände grafisch dargestellt werden

**Bug könnte mit #262 zusammenhängen**

**Comment by timobaehr** [comment]
Gelöst durch `1.11.38`.
