### ISSUE TITLE
Text der Zeitraumauswahl im Chart verschoben 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#274]
Tritt nur bei zweistelligem Tages- oder Monatsdatum auf. 

![Screenshot_20231224_173400.jpg](https://github.com/ehwplus/app-backlog/assets/127824087/e19134ff-203f-46fe-b5a3-6d0a4e926554)

**Comment by timobaehr** [comment]
Gelöst in `1.11.39`
