### ISSUE TITLE
Unvollständige Statistik bei mehr als 2 miteinander verlinkten inaktiven Zählern

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#285]
## IST:
Bei mehreren inaktiven Zählern, die korrekt mit dem nachfolgendem neuen Zähler verlinkt sind, werden im aktiven Zähler nur die Statistik des aktiven und des vorherigen Zählers angezeigt.

### Beispiel:

Gegeben sind 4 Stromzähler: 
Stromzähler 1: 01.01.23 bis 01.05.2023 (inaktiv; neuer Zähler: Stromzähler 2)
Stromzähler 2: 01.05.2023 bis 01.10.2023 (inaktiv; neuer Zähler: Stromzähler 3)
Stromzähler 3: 01.10.2023 bis 03.12.2023(inaktiv; neuer Zähler: Stromzähler 4)
Stromzähler 4: seit 03.12.2023 (aktiver Zähler)

| Zähler | angezeigte Statistik im Einzelzähler | 
| --- | --- |
| Stromzähler 1 | 01.01.2023 bis 01.05.2023 |
| Stromzähler 2 | 01.05.2023 bis 01.10.2023 |
| Stromzähler 3 | 01.10.2023 bis 03.12.2023 |
| Stromzähler 4 | seit 01.10. |

JSON zum Testen: 
[Testobjekt_2024-01-04_0400.json](https://github.com/ehwplus/app-backlog/files/13832297/Testobjekt_2024-01-04_0400.json)
 

## SOLL:
im aktiven Zähler soll die Statistik aller vorherigen Zähler angezeigt werden
Soll auch in den Statistiken der einzelnen inaktiven Zähler jeweils die Statistik der Vorgängerzähler dargestellt werden?

| Zähler | erwartete angezeigte Statistik im Einzelzähler | 
| --- | --- |
| Stromzähler 1 | 01.01.2023 bis 01.05.2023 |
| Stromzähler 2 | Stromzähler 1 & 2 ODER nur Stromzähler 2 |
| Stromzähler 3 | Stromzähler 1, 2 & 3 ODER Stromzähler 2 & 3 ODER nur Stromzähler 3 |
| Stromzähler 4 | seit 01.01.2023 (ab Stromzähler 1) |

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2163

**Comment by janine0407** [comment]
> Ich habe bereits 2 getauschte Wasserzähler und habe versucht die alten Zähler nach dem von Ihnen beschriebenen Vorgehen mit dem aktuellen, dritten Zähler zu verlinken. Leider fehlt mir in der Statistik immer 1 Zähler, entweder der erste oder der mittlere (der zweite). 

https://support.ehwplus.com/#ticket/zoom/2536

**Comment by timobaehr** [comment]
`1.12.4`
