### ISSUE TITLE
Ableseerinnerung 2-monatlich Ende enthält falsches nächstes Erinnerungsdatum 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#289]
## IST:

letzte Ablesung 31.10.2023, Zählerstand veraltet seit 31.12.2023, Erinnerung erschien am 31.12.2023
Nächste Erinnerung würde 31.03.2024 erfolgen.

![2024-01-07 11 03 37](https://github.com/ehwplus/app-backlog/assets/127824087/595ecd0d-8d8b-42ae-a746-95f90e1d6c59)

## SOLL:

Nächste Erinnerung 29.02.2024

**Comment by timobaehr** [comment]
1.11.43
