### ISSUE TITLE
Tooltip für Datenpunkt ganz links zeigt falsche Minimal-/Maximaltemperatur an

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#292]
Für fast alle Zeitraumauswahlen (außer Gesamtzeitraum?) wird im Verbrauchschart für den Tooltip ganz links anstelle der Maximaltemperatur die Minimaltemperatur der y-Achse angezeigt.
![photo_2024-01-09 07 11 08](https://github.com/ehwplus/app-backlog/assets/13302336/2aac83f1-208c-4426-beea-c560e0efd696)

In einem nicht nachstellbaren Fall stand bei einem Nutzer hier sogar -39,4°C, es stimmte also auch die Minimaltemperatur nicht.
![Image](https://github.com/ehwplus/app-backlog/assets/13302336/6302207a-24d2-41f8-9f46-d7abddc3a2d6)

**Comment by timobaehr** [comment]
https://t.me/ehwplus/3051/10493

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/10277
https://support.ehwplus.com/#ticket/zoom/2298

![IMG_20240109_082205_095.jpg](https://github.com/ehwplus/app-backlog/assets/127824087/cc1a2f6d-4fc5-4ae7-b6ce-5939819376a6)

**Comment by timobaehr** [comment]
Eventuell korrigiert in 1.11.44.
