### ISSUE TITLE
Im virtuellen Zählern wird nur max 1 inaktiver verlinkter Zähler berücksichtigt

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#293]
## IST:
Die Statistik des virtuellen Zählers ist falsch, wenn der Hauptzähler mehrmals getauscht, die älteren Zähler inaktiv gesetzt und miteinander verlinkt wurden. Es wird nur der aktive Zähler und max. 1 inaktiver Vorgängerzähler berücksichtigt. 

### Beispiel:

Gegeben sind:
Stromzähler 1: 01.01.23 bis 01.05.2023 (inaktiv; neuer Zähler: Stromzähler 2)
Stromzähler 2: 01.05.2023 bis 01.10.2023 (inaktiv; neuer Zähler: Stromzähler 3)
Stromzähler 3: 01.10.2023 bis 03.12.2023(inaktiv; neuer Zähler: Stromzähler 4)
Stromzähler 4: seit 03.12.2023 (aktiver Zähler)
Stromeinspeiszähler: seit 01.06.2023 (aktiv)
Stromerzeugniszähler: seit 01.06.2023 (aktiv)
virtueller Zähler: Hauptzähler = Stromzähler 1, Abzuziehender Zähler = Stromeinspeiszähler, Zu addierender Zähler = Stromerzeugniszähler 

In der Statistik des virtuellen Zählers werden zur Berechnung nur Stromzähler 3, Stromzähler 4, Stromeinspeiszähler und Stromerzeugniszähler genommen. Für die Zeit 01.06.2023 bis 01.10.2023 werden Stromeinspeiszähler und Stromerzeugniszähler addiert (falsche Statistik), da Stromzähler 2 nicht in die Berechnung einbezogen wird.

JSON zum Testen: 
[Testobjekt_2024-01-09_0200.json](https://github.com/ehwplus/app-backlog/files/13874169/Testobjekt_2024-01-09_0200.json)

## SOLL:
Im virtuellen Zähler sollen alle inaktiven Zähler, sofern miteinander verlinkt, in der Statistik berücksichtigt werden.

evtl. hängt dies mit #285 zusammen

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2163

**Comment by timobaehr** [comment]
`1.12.4`
