### ISSUE TITLE
Auswahl des Zeitraums merken

### ISSUE THREAD

**Issue by EHWPlusSupport** [ehwplus/app-backlog#30]
Als Nutzer möchte ich, dass die zuletzt getätigte Auswahl des Zeitraums bestehen bleibt.

# Akzeptanzkriterien

- Für einzelnen Zähler: Letzte Auswahl pro Zähler speichern
- Für Zählertyp: Die Auswahl des ersten Zählers in der Liste ist maßgebend
- Der zuletzt getätigte Zeitraum von Charts bleibt bestehen
- Der zuletzt getätigte Zeitraum des Kostenüberblicks bleibt bestehen

```
object
  counter
    - letzte Auswahl
```

**Comment by EHWPlusSupport** [comment]
https://support.ehwplus.com/#ticket/zoom/523

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/524

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/981

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1004

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1434

**Comment by janine0407** [comment]
> --- IS: ---
Aufruf Statistiken. Es wird immer die letzten 12 Monate angezeigt.
> 
> --- SHOULD: ---
> Letze persönliche Einstellung, die nach erneuten öffnen wieder angezeigt werden sollte.

https://support.ehwplus.com/#ticket/zoom/1830

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1874

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1903

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1912
