### ISSUE TITLE
Nach Objektwechsel Statistiken vom vorigen Objekt sichtbar

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#300]
Betroffene Statistiken:
- Raum-Chart

Nicht mehr betroffen:
- Verbrauchstext

**Comment by timobaehr** [comment]
> --- IS: ---
> Objekt in Statistiktab wechseln führt zu falscher Anzeige von Daten
> 
> --- SHOULD: ---
> ich sollte nach dem Objektwechsel auf dem Tab die selben Daten sehen, wie nach einem Tabwechsel 

https://support.ehwplus.com/#ticket/zoom/2424

**Comment by tafaust** [comment]
Nachfolge Ticket: https://github.com/ehwplus/app-backlog/issues/357
