### ISSUE TITLE
fehlerhafte Prognose saisonaler Zähler unter 12 Monate Ablesung 

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#313]
Gegeben: saisonaler Zähler mit Ablesungen unter 12 Monate. Die Prognose sollte wie bei nicht-saisonalen Zählern anhand der Werte der letzten 30 Tage gerechnet werden.

IST: 

Fehlerhafte Prognose im Testzähler mit Verbrauch von 1000 kWh/Monat (August, September und Oktober 2023)

JSON mit den Testdaten: 
[Testobjekt_2024-01-27_0742.json](https://github.com/ehwplus/app-backlog/files/14073409/Testobjekt_2024-01-27_0742.json)

![Screenshot_20240127_191241.jpg](https://github.com/ehwplus/app-backlog/assets/127824087/6e4da369-99ea-4bd7-9c7e-bc2458ec31fc)

Prognose der Monate:

November '23 = 9,827 kWh
Dezember '23 = 10,154 kWh
Januar '24 = 10,154 kWh
Februar '24 = 9,499 kWh
März '24 = 10,154 kWh
April '24 = 9,827 kWh
Mai '24 = 10,154 kWh
Juni '24 = 9,827 kWh
Juli '24 = 10,154 kWh

SOLL: 

Richtige Prognoseberechnung wie beim nicht-saisonalen Zähler

November '23 = 966,465 kWh
Dezember '23 = 998,681 kWh
Januar '24 = 998,681 kWh
Februar '24 = 934,25 kWh
März '24 = 998,681 kWh
April '24 = 966,465 kWh
Mai '24 = 998,681 kWh
Juni '24 = 966,465 kWh
Juli '24 = 998,681 kWh

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/10754

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2493

**Comment by timobaehr** [comment]
`1.12.11`
