### ISSUE TITLE
0-Personenhaushalt in Durchschnittsberechnung Chart und Verbrauchstext

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#322]
Gegebenheit:
- veränderter Personenhaushalt im Laufe der Jahre (01.03.2023 = 1 Person, 01.01.2023 = 2 Personen, Davor = 5 Personen)
- Zeitraumauswahl im Chart = Letztes Jahr

Bug in allen Charts, bei denen Durchschnittsverbrauch im Chart angezeigt wird und ein Verbrauchstext mit Vergleich dt. Durchschnittshaushalt ausgegeben wird. 
Strom = grauer Kasten gesamte Statistikseite
Wasser = fehlende Durchschnittslinien im Chart; Verbrauchstext = Angabe eines 0-Personenhaushalts
Gas = grauer Kasten statt Chart und Kostenüberblick; Verbrauchstext = Angabe eines 0-Personenhaushalts

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2509

im Ticket befindet sich bereinigte JSON-Datei

**Comment by timobaehr** [comment]
`1.12.3`
