### ISSUE TITLE
Zeitformatierung in Excel-Export ist 12-Stunden-Format

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#324]

**Comment by janine0407** [comment]
> --- IS: ---
> Excel Export Datum ist richtig aber Zeiteinträge alle AM!
> 
> --- SHOULD: ---
> json 15:00 Uhr. excel 3:00 Uhr richtig wäre aber auch 15:00 Uhr. Die Daten werden so falsch interpretiert, wenn mehr als ein Zählerstand am Tag ermittelt werden muss.

https://support.ehwplus.com/#ticket/zoom/2494

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2544

**Comment by timobaehr** [comment]
`1.12.5`
