### ISSUE TITLE
y-Achsen-Beschriftung bricht um im Verbrauchschart

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#326]
y-Achsen-Beschriftung bricht um im Verbrauchschart

![Image](https://github.com/ehwplus/app-backlog/assets/13302336/7b3e4d4d-85d9-4559-8ada-333bed1b40ff)

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2553

**Comment by janine0407** [comment]
s. auch #315 

> Scheint Zahlen mit bis zu 3 Zeichen zu betreffen, ab vier Zeichen (Tausender) ist die Anzeige richtig.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2441

Nutzerbild im Anhang

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11889

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/14057

**Comment by timobaehr** [comment]
Bitte erneut öffnen, wenn es immer noch zu wenig Pixel sind
