### ISSUE TITLE
Ableseerinnerung für bestimmten Tag

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#34]
Aktuell kann man sich zu Anfang und Ende eines wählbaren Zeitraums erinnern lassen, aber noch nicht sagen, dass man am x.y. erinnert werden will.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/723

**Comment by timobaehr** [comment]
--- IS: ---
wöchentliche Ableseerinnerung bei Beginn erinnert am Sonntag

--- SHOULD: ---
Beginn der Woche wäre für mich eigentlich der Montag.

https://support.ehwplus.com/#ticket/zoom/672

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/650

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/953

**Comment by timobaehr** [comment]
>Hallo,
>Ich fände es gut wenn man die Erinnerungen an bestimmten Tagen setzen könnte anstatt einem regelmäßigen Rhythmus.
>Ich lese z.B. immer am 15. und am letzten Tag des Monats ab...
>
>Ware schön wenn das in Zukunft als Erinnerung möglich wäre.

https://support.ehwplus.com/#ticket/zoom/1069

**Comment by janine0407** [comment]
> ich halte die Daten am 1. und 15. eines Monats fest.

https://support.ehwplus.com/#ticket/zoom/1210

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1275

**Comment by janine0407** [comment]
Der Nutzer hat einen Vorschlag zum individuellen Einstellen der Erinnerung gemacht. Im Ticket befinden sich Screenshots zur Veranschaulichung.

https://support.ehwplus.com/#ticket/zoom/1456

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2384

> Und, die Ableseerinnerung sollte auch so eingestellt werden, dass man einmal jährlich auch unter dem Jahr einen Ablesetermin angegeben kann.

> Und bei der Ableseerinnerung vermisse ich tatsächlich die Möglichkeit, dass man auch einen Termin unter dem Jahr definieren kann. Bei mir ist es nämlich so, dass ich Gas und Strom zum 1. April ablesen muss.

**Comment by timobaehr** [comment]
1.11.47
