### ISSUE TITLE
[iOS] Keine Anzeige der Außentemperatur auf iOS

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#348]
## IST:
Temperaturkurve bei saisonalen Zählern ist nicht vorhanden.
Android und WebApp nicht betroffen. 

## SOLL
Bei erfüllten Voraussetzungen: 
- PLZ eingetragen
- Als Land etwas ausgewählt (DE, CH, AT)
- App auf 1.9.0+ aktualisiert
- Premium-Abo läuft
- Chart eines saisonalen Zählers geöffnet
- Internetverbindung

soll die Temperaturkurve im Chart angezeigt werden.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2630

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11192

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11194

**Comment by tafaust** [comment]
Timo solved this ticket. New version released and approval is pending.

**Comment by timobaehr** [comment]
`1.12.13`
