### ISSUE TITLE
Zählerstände können nicht gefiltert werden

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#355]
## IST
Es werden alle Zählerstände in der Liste angezeigt, eine Filterung nach "Einträge mit Notiz" oder "An Anbieter übermittelt" ist nicht möglich. Die Auswahl wird nicht übernommen. 

#### Bug tritt auf: 
Android 14 (App Version 1.12.13, 1.12.15 und 1.13.3)
iOS 17.3.1 (App Version 1.12.15)

#### Bug tritt nicht auf: 
MacOS Sonoma 14 (App Version 1.12.13)
WebApp 1.12.12 
Android 13 (App Version 1.12.14)

## SOLL
Filterung sollte wieder möglich sein

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2642

**Comment by timobaehr** [comment]
Nicht nachstellbar auf Android 13-Gerät.

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11638

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11639

**Comment by timobaehr** [comment]
`1.13.10`
