### ISSUE TITLE
Haushaltsgröße/Personen für die Durchschnittslinie im Chart wird abgerundet - horizontale Linie ist falsch

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#356]
## IST
Im Chart (Wasser, Strom, Gas) richten sich die horizontalen Linien (Durchschnittsverbrauch) nach der Personenanzahl des Objektes. Durch die veränderbaren Haushaltsgrößen können für Zeiträume auch double (Dezimalzahlen) entstehen. 
Aktuell werden die Werte abgerundet. Das führt dazu, dass die Linien im Chart nicht mit dem Verbrauchstext übereinstimmen. 

Testobjekt: nur Kaltwasser ohne Warmwasser 
[Testobjekt_2024-02-28_1757.json](https://github.com/ehwplus/app-backlog/files/14437815/Testobjekt_2024-02-28_1757.json)

Verbrauchstext für Letztes Jahr: 1,8 Personen
Chart: horizontale Linie liegt bei 1 Person (ca. 3.862 m3) 
Soll: für 1,8 Personen bei ca. 6.953m3 

![2024-02-28 18 06 26](https://github.com/ehwplus/app-backlog/assets/127824087/3c91c852-a521-4581-8029-69091c931939)

## SOLL
Chart und Verbrauchstext sollen stimmig sein. 
Hierfür soll für den Chart die Haushaltsgröße nicht auf Ganzzahl gerundet werden sondern dieselbe Haushaltsgröße (double) verwenden wie im Verbrauchstext.

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11259

Im Text steht ein 4-Personenhaushalt, im Chart hingegen ist die Durchschnittslinie für einen 3-Personenhaushalt. 
(Die tatsächliche Haushaltsgröße für den Zeitraum liegt bei 3,9945... Personen)

![2024-02-28 17 35 10](https://github.com/ehwplus/app-backlog/assets/127824087/715ab90b-12b5-46a2-a9ad-3439e1b38ce7)

**Comment by timobaehr** [comment]
`1.12.14`
<img width="693" alt="Bildschirmfoto 2024-03-02 um 16 30 55" src="https://github.com/ehwplus/app-backlog/assets/13302336/1c35eaa0-9e70-4d76-a470-1c2cdfc2bd47">
