### ISSUE TITLE
Bei langen Notizen soll Ablesescreen scrollbar sein

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#358]

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11277

![telegram-cloud-photo-size-2-5398081074648699703-y](https://github.com/ehwplus/app-backlog/assets/127824087/167c9375-1f96-4128-b8b5-7dc4e7ac5b82)

**Comment by timobaehr** [comment]
`1.12.14`
