### ISSUE TITLE
Haushaltsgröße im Verbrauchstext <1,0 verursacht grauen Kasten bei Gesamtstatistik

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#360]
## IST
Gesamtstatistik = grauer Kasten
Verbrauchstext kann nicht erstellt werden, da mit Haushaltsgröße <1 (gerundet auf 0) gerechnet wird und hierfür keine Vergleichswerte existieren. 

## SOLL
Haushaltsgröße kann nicht niedriger als 1 sein. 

<img width="433" alt="Bildschirmfoto 2024-03-02 um 14 23 46" src="https://github.com/ehwplus/app-backlog/assets/13302336/e40fc802-b334-4f05-b4f9-c79b492f3cd6">

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2677

bereinigte JSON im Ticket

**Comment by timobaehr** [comment]
https://t.me/ehwplus/3345/11325

**Comment by timobaehr** [comment]
`1.12.14`
