### ISSUE TITLE
Vom Gesamtverbrauch ausgeschlossene Zähler mit Chart und Heatmap in Gesamtstatistik anzeigen

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#361]
Zähler, die vom Gesamtverbrauch ausgeschlossen werden, sollen in der Gesamtstatistik im Chart und mit Heatmap angezeigt werden aber nicht im Kostenüberblick hinzugerechnet werden.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2584

**Comment by timobaehr** [comment]
`1.12.14`

**Comment by timobaehr** [comment]
Änderungen rückgängig gemacht. Es ist inkonsistent. Man müsste dann Statistiken mehrerer Zähler vermsichen mit Statistiken von Einzelzählern. Das könnte sehr unübersichtlich werden. Ausgeschlossene Zähler werden unten verlinkt, darüber kommt man an die Einzelstatistik.
