### ISSUE TITLE
Auswertung pro Zimmer

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#371]
Zählern kann ein Zimmer zugeordnet werden. In der Gesamtstatistik erscheint dann ein Balkendiagramm. Ein Nutzer wünscht sich, dass die Statistiken für ein Zimmer besser zugänglich werden auch mit Chart und Heatmap.

**Comment by janine0407** [comment]
ist das ähnlich zu #264?

**Comment by timobaehr** [comment]
Ja, ich schließe das hier. Danke!
