### ISSUE TITLE
Anmeldung Google Drive Sync in WebApp nicht möglich

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#382]
## IST:
In der aktuellen Version 1.13.4 der Web-App erscheint im Reiter Sync nach Tap auf den Button "Anmelden mit Google" die Abfrage nach dem Google-Konto. Danach passiert nix, eine Anmeldung erfolgt nicht. Sync nicht möglich. 

Browser:
Chrome
Safari

<img width="1470" alt="Bildschirmfoto 2024-03-18 um 14 08 43" src="https://github.com/ehwplus/app-backlog/assets/127824087/c47aad83-4929-40be-a81f-2fd6dace9b7d">

## SOLL:
Anmeldung bei Google Drive Sync sollte wieder möglich sein.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2651

**Comment by tafaust** [comment]
Ebenfalls reproduzierbar in der App.
