### ISSUE TITLE
Briefumschlag-Icon statt Kopieren-Icon in Debug Log-View verwenden

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#385]
In den Debug Log-Views wird für das Versenden/Öffnen der Mail-App das Kopieren-Icon verwendet. Das ist für den Nutzer irritierend und nicht intuitiv. Es könnte durch ein Briefumschlag-Icon (wie bei "Vorschlag machen") o.ä. ersetzt werden.

**Comment by janine0407** [comment]
> Es ist nicht intuitiv, dass ein Kopieren-Icon das E-Mail-Programm öffnet. Da sollte stattdessen das "send"-Icon oder sowas sein

https://t.me/ehwplus/3051/11727

**Comment by tafaust** [comment]
@janine0407 Done

**Comment by timobaehr** [comment]
`1.13.7`
