### ISSUE TITLE
Klarer visueller Unterschied zwischen Statusermittlung und Synchronisation

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#386]
Als Nutzer der App möchte ich eine eindeutige visuelle Unterscheidung zwischen der Statusermittlung und der Synchronisation haben, um zu wissen, ob die App gerade synchronisiert oder lediglich den Status überprüft.

**Comment by janine0407** [comment]
> Das ist irgendwie nicht intuitiv, dass die App da etwas tut, das genauso aussieht wie die Synchronisierung, obwohl die automatische Synchronisierung abgeschaltet ist.

https://t.me/ehwplus/3051/11740

**Comment by Discostu36** [comment]
Evtl. könnte man z.B. die Animation im linken Icon nur für die Synchronisation nutzen, den Untertitel hingegen auch für Status-Ermittlungen o.Ä.

**Comment by timobaehr** [comment]
`1.13.9`
