### ISSUE TITLE
Änderung Personenanzahl wird nicht gespeichert

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#399]
## IST:

- Personenanzahl/Haushaltsgröße kann nicht über Pfeile geändert werden
- als Zahl eingetragene Personenanzahl bleibt nicht gespeichert

## SOLL:

Die Personenanzahl soll über Pfeile (hoch/runter) wie auch über die Tastatur geändert werden können und gespeichert bleiben.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2772

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11864

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2774

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2775

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2778

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2783

**Comment by timobaehr** [comment]
`1.14.4`
