### ISSUE TITLE
Personenzahl sollte auf 1 gestellt werden können

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#400]
Ich kann die Personenzahl eines neuen Objekts nicht auf 1 Stellen. Standardmäßig war es auf 2.
Die Pfeile, um die Zahl zu ändern, funktionieren übrigens auch nicht.

**Comment by timobaehr** [comment]
https://t.me/ehwplus/3051/11864

**Comment by janine0407** [comment]
Duplikat von #399
