### ISSUE TITLE
Tageswert bei Gas um Faktor 100 zu hoch - Statistik falsch

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#404]
## IST:

Test-JSON: [Testobjekt_2024-04-03_1520.json](https://github.com/ehwplus/app-backlog/files/14863895/Testobjekt_2024-04-03_1520.json)

- Gaszähler in Einheit m3
- Brennwert: 10, Zustandszahl: 1,0 unverändert
- Zählerstand 01.01.23: 0 m3 (0 kWh)
- Zählerstand 01.01.24: 100 m3 (1.000 kWh)

Auf Zählerständeseite wird die Gesamtdifferenz in m3 und kWh zwischen zwei Zählerständen richtig angezeigt.
Berechnung pro Tag ist um den Faktor 100 zu hoch.
Werte in der Statistik für tatsächlichen Verbrauch stimmen dadurch auch nicht, Prognosewerte hingegen schon. 

| Zählerstände | Statistik | 
| --- | --- | 
|![2024-04-04 10 38 50](https://github.com/ehwplus/app-backlog/assets/127824087/2bbcafd9-15c9-4b77-a9bd-c51676dc12e6)| ![2024-04-04 10 38 54](https://github.com/ehwplus/app-backlog/assets/127824087/fbf1d88d-2ada-4bb1-adf1-7a39964a8a2a)|

## SOLL:

Tagesverbrauch aus Zählerständeseite: 2,7397 kWh
Statistik Kostenüberblick für 2023: 1.000 kWh

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2772

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2777/9784

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2779

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/11893

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2786

**Comment by timobaehr** [comment]
`1.14.5`

**Comment by janine0407** [comment]
Zwischen den einzelnen Zählerständen ist der Bug gefixt.
Fehler tritt aber immer noch in der Einzelstatistik sowie in der Gesamtstatistik auf. 

![2024-04-10 15 19 56](https://github.com/ehwplus/app-backlog/assets/127824087/6785c564-dce2-4bb0-baa2-c170338cb96e)

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2814/9886

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2818

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2772

> Soweit alle supi, aber es existiert immer noch eine Fehler bei der Statistik Übersicht für Gas.
Ich sende ihnen ein Screenshot mit.

Screenshot im Anhang des Tickets

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2824

> --- IS: ---
> Statistiken für neu eingetragenen Gaszähler werden falsch angezeigt. Täglicher Verbrauch von mehr als 2000 kWh bei Gesamtverbrauch von 39,545 m^3 im Berechnungszeitraum.
> 
> --- SHOULD: ---
> Der durchschnittliche Verbrauch sollte bei ca. 24 kWh pro Tag liegen
> 
> --- PAGES: ---
> Statistik des Gaszählers, Statistik allgemein

**Comment by janine0407** [comment]
> Nach wie vor sind die statistischen Werte nicht in Ordnung. Ich hänge mal ein Bild an, wo die fehlerhaften Berechnungen zu sehen sind. Es werden utopische Verbräuche angezeigt. Ich denke, dass die Kommastellen verrutscht sind.
> So sind die statistischen Berechnungen wertlos.

https://support.ehwplus.com/#ticket/zoom/2786

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2834

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2831

**Comment by timobaehr** [comment]
Korrigiert in `1.14.12`
