### ISSUE TITLE
Oberfläche in Ableseseite für Einheit m3 / Liter stürzt ab

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#411]
Betroffen: Gas, Wasser (aber aktuell nicht nachstellbar)

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2793

**Comment by janine0407** [comment]
https://t.me/ehwplus/3051/12052

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2794

**Comment by timobaehr** [comment]
Triff der Fehler unverändert auf? Sollte gelöst sein durch `1.14.2`.
