### ISSUE TITLE
Wert für anteiligen Verbrauch bzw. Faktor für Zähler vom Typ Heizkörper können nicht geändert werden

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#413]
## IST:
Bei Zählern, bei denen der anteilige Verbrauch eingetragen werden kann, wird eine Änderung sowie ein neu hinzugefügter Wert nicht gespeichert. 

## SOLL:
Speicherung der Änderung und Speicherung eines neuen Wertes

**Comment by janine0407** [comment]
> Ich kann leider den Anteiligen Verbrauch nicht einstellen. Egal was ich eingebe, es bleibt immer bei 1,0

https://t.me/ehwplus/3051/12093

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/2805

**Comment by timobaehr** [comment]
Fixed in `1.14.10`

**Comment by janine0407** [comment]
> Beim KaltwasserZähler kann ich immer noch keinen Anteil einstellen

> Der Teile stellt sich immer wieder auf 1,0 zurück

https://t.me/ehwplus/3051/12249
https://t.me/ehwplus/3051/12271

**Comment by janine0407** [comment]
> Ich habe festgestellt, dass in der Web-Version grundsätzlich bei Heizung kein Faktor mehr gespeichert wird, auch wenn man diesen eingibt steht beim nächsten Öffnen dort ein Faktor von 1 wieder

https://t.me/ehwplus/3051/12278

**Comment by timobaehr** [comment]
`1.14.13`
