### ISSUE TITLE
Stromerzeugungszähler

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#42]
Mit bereits hinzugefügten Einspeiszähler wird ermittelt, wie viel durch Sonne erzeugte Energie ins Stromnetz eingespeist und damit vergütet wurde. Es fehlt aktuell jedoch noch ein Erzeugniszähler, um ablesen zu können, wie viel des erzeugten Stroms selbst verbraucht wurde.

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/851

**Comment by janknieling** [comment]
Hi @timobaehr,

Für das Feature gibt es schon einen Issue. Ich hatte dafür vor einer Weile #31 aufgemacht

**Comment by timobaehr** [comment]
Haste recht, danke!
