### ISSUE TITLE
lange Ladezeiten der Gesamtstatistiken

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#420]
## IST: 
Die Charts im Tab Statistik haben teils sehr lange Ladezeiten. 

subjektive Beobachtung: Bei Objekten mit weniger Daten laden die Charts schnell, während bei Objekten mit mehr Daten die Charts sehr langsam geladen werden. 

Auch in den einzelnen Gesamtstatistiken laden die Charts bei größeren Datenmengen langsamer als bei weniger großen Objekten. Der Kostenüberblick benötigt teilweise nochmal einige Sekunden bis Minuten länger bis er vollständig geladen ist. 

## SOLL:
Statistiken sollten schneller geladen werden

**Comment by janine0407** [comment]
> Also aktuell laden die Statistiken bei mir noch sehr langsam. Die Statistiken für die Heizung brauchen ca 4-5 Sekunden ehe sie angezeigt werden und laden dann immernoch nach.

https://t.me/ehwplus/3051/12286

**Comment by janine0407** [comment]
> Das Laden der Statistikdaten dauert sehr lange (>5min)

https://support.ehwplus.com/#ticket/zoom/2886

**Comment by timobaehr** [comment]
1.16.0
