### ISSUE TITLE
Teilen von gespeicherten Zählerfotos 

### ISSUE THREAD

**Issue by EHWPlusSupport** [ehwplus/app-backlog#43]
![Screenshot_20230205-184619](https://user-images.githubusercontent.com/122748312/216836404-fb2ade18-052d-4e77-af95-83ad16a4d151.png)

Der Teilen-Button funktioniert nicht

Version 1.7.25 build 446

**Comment by timobaehr** [comment]
@EHWPlusSupport Bei mir funktioniert es einwandfrei. Was genau ist falsch auf welchem Gerät?

**Comment by EHWPlusSupport** [comment]
Kann geschlossen werden.
Funktioniert bei mir auch wieder

**Comment by EHWPlusSupport** [comment]
Funktioniert wieder
