### ISSUE TITLE
Import Zählerstände mit 3 Dezimalstellen

### ISSUE THREAD

**Issue by tbotbo** [ehwplus/app-backlog#455]
Hat eine Importdatei 3 Dezimalstellen (bei Gas verwendet), so übergeht der Import alle Zeilen mit Werten >999 (vor dem Komma). Diese Importdatei mit nur 2 Dezimalstellen wird fehlerfrei verarbeitet.

**Comment by janine0407** [comment]
Danke, dass du den Fehler gemeldet hast. Um uns zu helfen, das Problem schneller zu identifizieren und zu beheben, benötigen wir noch ein paar zusätzliche Informationen. Könntest du bitte die folgenden Details ergänzen:

**Detaillierte Beschreibung des Problems:**

Was genau passiert? 

**Beispiel-CSV-Datei:**

Könntest du eine Beispiel-CSV-Datei bereitstellen, die das Problem zeigt? Sende sie ggf. bitte an bug@ehwplus.com unter Bezugnahme auf dieses Issue.

**Schritte zur Reproduktion:**

Welche Schritte sind erforderlich, um den Fehler zu reproduzieren? Zum Beispiel:

1. Im Bereich Import CSV-Datei auswählen
2. Fortsetzen drücken
3. Faktor x,x eingeben
4. Fortsetzen drücken
5. "Neuen Zähler anlegen" oder bestehenden Zähler auswählen 
6. Einstellungen der Zähler, zB Einheit, Brennwert/Z-Zahl, Nachkommastellen

**Erwartetes Ergebnis:**

Was hast du erwartet, dass passieren sollte?

**Tatsächliches Ergebnis:**

Was passiert tatsächlich?

**Gerätedaten:**

- Gerät: (z.B. Samsung Galaxy S21)
- Betriebssystem: (z.B. Android 11)
- App-Version: (z.B. 1.14.19)

Falls möglich, wären Screenshots oder Videos, die das Problem zeigen, ebenfalls sehr hilfreich. Du kannst diese Dateien direkt hier anhängen. Wenn die Informationen sensible Daten enthalten, sende sie bitte an bug@ehwplus.com.
Vielen Dank für deine Mithilfe!

**Comment by tbotbo** [comment]
CSV und Screenshot sind angefügt.

Vorgehen:
1. Im Bereich Import CSV-Datei auswählen

Bereits hier sieht man das Problem: Alle Zeilen der Importdatei werden ignoriert.
Hat man hier eine CSV mit nur 2 Dezimalstellen, geht der Import fehlerfrei durch.

Gerätedaten:

Gerät: Samsung Galaxy Note10+
Betriebssystem: Android 12
App-Version: 1.14.17 - auch in der Web-App reproduzierbar.

Beste Grüße!

[Gas.csv](https://github.com/user-attachments/files/16071889/Gas.csv)
![24-07-02 19_03_52-EHW+ Import](https://github.com/ehwplus/app-backlog/assets/50994118/54206064-879b-4661-aa35-b6530d2a931f)

**Comment by janine0407** [comment]
Hallo,

danke für die genauen Informationen. Ich kann erkennen, dass die Werte in der zweiten Spalte im falschen Format sind. Das Tausendertrennzeichen wird beim Import nicht erkannt. Bitte die Werte ändern auf bspw. 10619.937 oder 10619,937; dann sollte es möglich sein auch mit drei Dezimalstellen zu importieren. 
Bitte gern eine Rückmeldung hierzu geben oder melden, wenn es weiterhin nicht funktioniert. Beste Grüße, Janine

**Comment by janine0407** [comment]
Hallo,

da seit meiner letzten Antwort keine weitere Rückmeldung gekommen ist, werde ich dieses Issue vorerst schließen. Sollte  das Problem weiterhin bestehen, kann das Issue jederzeit wieder geöffnet oder ein neues erstellt werden.

Beste Grüße,
Janine
