### ISSUE TITLE
Import Zählerstände mit Werten >999

### ISSUE THREAD

**Issue by tbotbo** [ehwplus/app-backlog#456]
Importiert man eine CSV, wo alle Werte >999 sind, so werden sie falsch interpretiert und mit Faktor 0,001 multipliziert. Aus z. B. 1035 kWh werden 1,035 kWh. Ein Wert "0" in der Tabelle verhindert nicht die Fehlinterpretation. Nur wenn mindestens ein Wert zwischen 1 und 999 in der Tabelle enthalten ist, wird fehlerfrei importiert. 
Eine hilfsweise Verwendung des Faktors "1000" führt ebenso nicht zu korrekten Ergebnissen, die importierten Werte sind identisch mit dem oben beschriebenen Beispiel.

Info: Diese Importdatei enthält keine Tausendertrennzeichen und keine Dezimalstellen.

**Comment by janine0407** [comment]
Danke, dass du den Fehler gemeldet hast. Um uns zu helfen, das Problem schneller zu identifizieren und zu beheben, benötigen wir noch ein paar zusätzliche Informationen. Könntest du bitte die folgenden Details ergänzen:

**Beispiel-CSV-Datei:**

Könntest du eine Beispiel-CSV-Datei bereitstellen, die das Problem zeigt? Sende sie ggf. bitte an bug@ehwplus.com unter Bezugnahme auf dieses Issue.

**Schritte zur Reproduktion:**

Welche Schritte sind erforderlich, um den Fehler zu reproduzieren? Zum Beispiel:

1. Im Bereich Import CSV-Datei auswählen
2. Fortsetzen drücken
3. Faktor x,x eingeben
4. Fortsetzen drücken
5. "Neuen Zähler anlegen" oder bestehenden Zähler auswählen 
6. Einstellungen der Zähler, zB Einheit, Brennwert/Z-Zahl, Nachkommastellen

**Erwartetes Ergebnis:**

Was hast du erwartet, dass passieren sollte?

**Tatsächliches Ergebnis:**

Was passiert tatsächlich?

**Gerätedaten:**

- Gerät: (z.B. Samsung Galaxy S21)
- Betriebssystem: (z.B. Android 11)
- App-Version: (z.B. 1.14.19)

Falls möglich, wären Screenshots oder Videos, die das Problem zeigen, ebenfalls sehr hilfreich. Du kannst diese Dateien direkt hier anhängen. Wenn die Informationen sensible Daten enthalten, sende sie bitte an bug@ehwplus.com.
Vielen Dank für deine Mithilfe!

**Comment by tbotbo** [comment]
Seit ich den App-Cache gelöscht habe, lässt sich der Fehler nicht mehr reproduzieren.
