### ISSUE TITLE
App sollte mit Flutter 3.24 starten

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#475]
App kann wegen veralteter Anhängigkeit im Package `excel` und `archive` nicht mehr gestartet werden. 

Verwende vorerst Flutter `3.22.3` vor Release der neuen Versionen mit alter Dart-Version

Related issues:
- https://github.com/justkawal/excel/issues/364
- https://github.com/brendan-duncan/archive/issues/350

**Comment by tafaust** [comment]
Temporary solutions exists: https://github.com/justkawal/excel/issues/364#issuecomment-2294430837
