### ISSUE TITLE
[Stadtwerk ändern] Tippfehler: Gemeindewasserwerk Nonnweiler

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#497]

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/3179

> Wenn ich "new" eintippe, wird das "Gemeinewasserwerk Nonnweiler" angezeigt, wegen des Tippfehlers bei "Gemeinde"...
Bitte den Tippfehler berichtigen.

**Comment by timobaehr** [comment]
1.16.0
