### ISSUE TITLE
Dynamische Personenzahl / Haushaltsgröße

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#5]
Aktuell wird im Objekt einmalig festgelegt, wie viele Personen im Objekt wohnen. Eine Änderung führt auch zu einer Änderung in der Vergangenheit. Nicht berücksichtigt werden kann, ob z.B. für 2 Wochen Gäste kommen, der Auszug des Kindes, usw.

Es wurde ein Feature-Vorschlag erstellt.

## Design

| Inital | 1 Wert hinzugefügt |
|--------|--------|
|  <img width="421" alt="Bildschirmfoto 2024-01-24 um 19 09 39" src="https://github.com/ehwplus/app-backlog/assets/13302336/33e63d50-dedd-4079-83c8-aedd328808eb">  |  <img width="421" alt="Bildschirmfoto 2024-01-24 um 19 09 10" src="https://github.com/ehwplus/app-backlog/assets/13302336/ec3a7ed6-b9f9-4a13-b269-dd9ac1560d03"> |

## Konzept für Speicherung
`TimeVaryingData`-Datenstruktur
![EHW+(3)](https://github.com/ehwplus/app-backlog/assets/13302336/bdb67e46-db41-4d3e-be8e-cfa238b77c10)

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1267

**Comment by janine0407** [comment]
https://t.me/ehwplus/3345/8769

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2305
