### ISSUE TITLE
Kein Import der automatisch exportierten object.json möglich

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#507]
## Beschreibung des Problems

In den Einstellungen kann unter Sichern/Wiederherstellen im Tab Export die Funktion "Im lokalen Download-Ordner speichern" aktiviert werden. Die automatisch gespeicherte Datei object.json lässt sich nicht wieder in die App importieren. 

## Schritte zur Reproduktion

1. App öffnen
2. Einstellungen öffnen
3. Auf "Sichern/Wiederherstellen" drücken
4. Im Tab Export den Toggle "Im lokalen Download-Ordner speichern" auf ja stellen
5. Im Objekt etwas ändern bspw. einen neuen Zählerstand eintragen
6. im Download Ordner prüfen, ob Datei object.json gespeichert wurde
7. App wieder öffnen
8. Einstellungen öffnen
9. Auf "Sichern/Wiederherstellen" drücken
10. Tab Import auswählen
11. Auf "JSON-Datei (erstellt mit EHW+)" tippen
12. Vorher exportierte Datei object.json auswählen
13. es passiert nix

## Erwartetes Ergebnis

Die JSON-Datei erscheint im Punkt 1 des Imports als ausgewählt und in orange. Der Button "Fortsetzen" ist orange und aktiv.

## Tatsächliches Ergebnis

Es ist keine JSON-Datei zum Import ausgewählt, der Fortsetzen-Button bleibt grau und inaktiv.

## App-Version

1.14.29

## Logs 

<img width="1155" alt="Bildschirmfoto 2024-11-06 um 12 49 42" src="https://github.com/user-attachments/assets/3a54ac3e-3121-4a4b-9ef3-4047164e6258">

**Comment by janine0407** [comment]
> der Import mit der automatisch erzeugten Datei object.json geht leider nicht

https://support.ehwplus.com/#ticket/zoom/3211

**Comment by timobaehr** [comment]
Die geschriebene JSON-Datei ist nicht richtig encodiert und zumindest bei mir wird sie gar nicht neu geschrieben...
![Bildschirmfoto 2024-12-01 um 20 38 51](https://github.com/user-attachments/assets/04f0ad91-fb64-44a0-8fab-75676a8458f5)

**Comment by timobaehr** [comment]
In `local_storage_service.dart` Zeile 304
```dart
await objectFile.writeAsBytes(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes))
```
kommt es zu folgendem Fehler `PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/EHW+/<objectId>/object.json' (OS Error: Permission denied, errno = 13)`

Löschen des Objekt-Ordners hat dazu geführt, dass das Objekt wieder geschrieben werden konnte. Aber der Import-Fehler bleibt bestehen.

**Comment by timobaehr** [comment]
Wenn ich die Datei vom Handy auf den PC speichere und dann im Web importiere, geht der Import seltsamerweise.
