### ISSUE TITLE
[Web-App] Abo wird nicht erkannt

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#509]
## Beschreibung

Abo wird in der Web-App nicht erkannt/synchronisiert trotz erteiltem Consent, Sync mit selber Google-Mail.

## Erwartetes Ergebnis
Premium sollte auch im Web verfügbar sein. 

##Tatsächliches Ergebnis
Premium ist im Web nicht verfügbar, Sync der Objekte funktioniert. 

## App-Version
Web-App: 1.14.28

## Geräte und Umgebung

Betriebssystem: Windows 11, Version 23H2
Browser: Microsoft Edge, Version 130.0.2849.68

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/3221

Abo neu abgeschlossen am 1.11.24

**Comment by timobaehr** [comment]
@janine0407 Ist das Ticket noch aktuell nach Einführung des Nutzerkontos?

**Comment by janine0407** [comment]
> @janine0407 Ist das Ticket noch aktuell nach Einführung des Nutzerkontos?

Nein, ist nicht mehr aktuell. Mit der Einführung des Nutzerkontos haben sich die Bedingungen des Käufe-Sync geändert. Ich schließe das Ticket.
