### ISSUE TITLE
Manueller Export in "Lokaler App Ordner"

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#510]
Als Nutzer der App möchte ich die Möglichkeit haben, meine Dateien wieder manuell zu exportieren, damit ich eigenständig mehrere Backups (verschiedene Versionen) meiner Dateien speichern kann und nicht nur auf den automatischen Export angewiesen bin, bei dem ältere Versionen überschrieben werden.

**Zusätzlicher Kontext:**
Früher konnten Nutzer durch die manuelle Export-Funktion flexibel Sicherungskopien anlegen und so verschiedene Versionen der Daten speichern. Mit dem aktuellen automatischen Export (seit App-Version 1.14.28) gehen ältere Dateiversionen verloren, was den Nutzern das Vertrauen in die Datensicherheit nimmt.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/3211

**Comment by timobaehr** [comment]
Wurde umgesetzt. Ordner "Downloads/EHW+" bei Android und "EHW+" bei iOS. Ein Import aus diesem Ordner ist aktuell noch nicht implementiert.
