### ISSUE TITLE
[iOS/MacOS] App-Absturz bei Paketkauf

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#525]
## 1. Beschreibung 

Bei Tap auf den "Kaufen"-Button eines Pakets schließt sich die App ohne Fehlermeldung

## 2. Erwartetes Verhalten

Bei Tap auf den "Kaufen"-Button eines Pakets kann der Kauf fortgeführt werden.

## 3. Schritte zur Reproduktion des Fehlers

1. App öffnen
2. Ins Einstellungsmenü gehen
3. Auf "Upgrade" tippen
4. Ein Paket auswählen und auf "Kaufen" Button drücken

-> App schließt

## 4. Technische Details

Beriebssystem: iOS 18.2., MacOS
App-Version: 1.15.1 und 1.16.1

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/3341

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/3377

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/3384

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/3384

**Comment by ReH62** [comment]
Ticket can be closed, error is fixed

**Comment by janine0407** [comment]
Fixed in Version 1.16.3
