### ISSUE TITLE
Ableseerinnerung an bestimmten Tagen

### ISSUE THREAD

**Issue by EHWPlusSupport** [ehwplus/app-backlog#54]
Hallo,
Ich fände es gut wenn man die Erinnerungen an bestimmten Tagen setzen könnte anstatt einem regelmäßigen Rhythmus.
Ich lese z.B. immer am 15. und am letzten Tag des Monats ab...

Ware schön wenn das in Zukunft als Erinnerung möglich wäre.

**Comment by EHWPlusSupport** [comment]
[https://support.ehwplus.com/#ticket/zoom/1069](url)

**Comment by EHWPlusSupport** [comment]
[https://github.com/ehwplus/app-backlog/issues/34](url)

**Comment by timobaehr** [comment]
Duplikat von #34
