### ISSUE TITLE
Einfärben des Verbrauchs in Heatmap auf Tagesbasis

### ISSUE THREAD

**Issue by EHWPlusSupport** [ehwplus/app-backlog#57]
Die graphischen Anzeigen werden der Monatsstatistiken durch die verschiedenen langen Monate leicht verfälscht; zwischen 30 und 31 Tagen ist dies ja überschaubar im Rahmen von 3-4 Prozent, zwischen Februar und März bzw. Januar liegt der Einfluss der Monatslänge aber schon bei rd 10 %, sodass man im Februar einen "Verbrauchsknick" durchaus beobachten kann.

Mein Vorschlag wäre, in der Heatmap und dem Chart wahlweise die für den Monat errechneten Rohdaten (wie bisher) zu plotten oder einen normalisierten Wert, z. B. auf 30 Tage. In einfachster Umsetzung könnte man z. B. den bisherigen Monatswert mit 30/31 multiplizieren (für Monate mit 31 Tagen) bzw. mit 30/28 (für den Februar in nicht-Schaltjahren bzw 30/29 in Schaltjahren).

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1151

**Comment by timobaehr** [comment]
f79dab5c impr(57): Use daily consumption for background cell color instead total consumption
