### ISSUE TITLE
Heatmap optional ein-/ausblenden

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#60]
Die Verbrauchs-Heatmap könnte unter Einstellungen ein-/ausblendbar geschaltet werden.
Für Nutzer, die weniger als 1x/Monat Zählerstände eintragen, hat die Heatmap kaum/keine Aussagekraft und ist störend.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1181

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1970

**Comment by timobaehr** [comment]
https://github.com/ehwplus/ehwplus_flutter/pull/149
