### ISSUE TITLE
Gaspreisbremse Berechnung Jahresverbrauch 2021 und Entlastungskontingent falsch

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#66]
IST:
Bezug des Werts für den Jahresverbrauch 2021 bei der Gaspreisbremse unklar, dadurch auch fehlerhafte Berechnung Entlastungskontingent. 

SOLL:
richtige Wertermittlung Jahresverbrauch 2021 des Gaszählers für die Gaspreisbremse

**Comment by janine0407** [comment]
iOS: https://support.ehwplus.com/#ticket/zoom/1215

**Comment by janine0407** [comment]
Testzähler Gas Android: 
![photo_2023-03-20_12-19-06](https://user-images.githubusercontent.com/127824087/226325362-dccbd93b-10d0-4b3c-b024-ecbcc279cf68.jpg)
![photo_2023-03-20_12-18-56](https://user-images.githubusercontent.com/127824087/226325369-7c17a6b6-6df1-45e9-b228-d9df7695a4a9.jpg)

**Comment by timobaehr** [comment]
Sieht bei mir korrekt aus?
![photo_2023-04-02 13 37 36](https://user-images.githubusercontent.com/13302336/229350391-88b91124-b008-4c78-9886-29d21da6195a.jpeg)
