### ISSUE TITLE
Strom- und Gaspreisbremse DE&AT - Zwei Kommastellen beim geringeren Preis

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#70]
Der geringere Preis sollte mit 6 Kommastellen eingegeben werden können!

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1119

**Comment by timobaehr** [comment]
0f33d2b2  impr(70): reduced price with 6 fraction digits
