### ISSUE TITLE
Abschlag Stromeinspeiszähler

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#81]
Im Vertrag für den Stromeinspeiszähler fehlt das Feld zur Eingabe des Abschlages (monatliche Vorauszahlung), welcher vom Stromnetzbetreiber gezahlt wird.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1213
https://support.ehwplus.com/#ticket/zoom/2154

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1316

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2154

**Comment by timobaehr** [comment]
1.11.26
