### ISSUE TITLE
InApp-Hinweis "Zählerstand veraltet" erscheint zu früh

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#87]
Als Nutzer möchte ich mich an Ablesungen erinnern lassen können. Dabei gibt es zwei Mechanismen:
1.) Die App ist geschlossen und es erscheint eine Benachrichtigung in der Benachrichtigungsleiste
2.) Die App ist geöffnet und ein Glocken-Icon signalisiert, ob es Zähler gibt, bei denen eine Ablesung gemacht werden sollte.

Funktionalität 2 ist ähnlich zu 1, aber nicht gleich. Bei 1, dem Benachrichtigungszeitpunkt, liegt der Zeitpunkt immer in der Zukunft. Bei Funktionalität 1 benötigt man den Zeitpunkt, an dem der Zählerstand nicht mehr aktuell war. 

## Code-Hinweise

Im Code gibt es `scheduleMeterReadingReminders` im `ReadingReminderService` (1) und `Counter.isOutdated` (2). Die Funktionalität ist ähnlich, aber `isOutdated` funktioniert nicht richtig, weil in der App Zähler zu früh als veraltet markiert werden.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1208

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1252

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1083
