### ISSUE TITLE
Brennwert und Z-Zahl für Gas zeitvariabel

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#9]
Z-Zahl und Brennwert kann sich mit jeder Ablesung ändern. Es ist daher falsch, wenn man diesen Wert an den Zähler knüpft. Bisher muss nach einer Änderung dieser Werte ein "Zählerwechsel durchgeführt" werden.

## Technische Betrachtung

Aktuell werden in `counterEntries` zwei Werte gespeichert: (1) `gasConversionFactor` und (2) `gasCalorificValue`. Daraus ergibt sich der `entryValueFactor`.

Künftig könnten diese Werte in jedem `CounterEntry` gespeichert werden, was aber zu erheblicher Redundanz führen würde. Wenn der Nutzer die Werte rückwirkend ändern will, müssten alle Einträge der Vergangenheit angepasst werden.

Alternativ könnten die Werte immer mit Zeitpunkt gespeichert werden, ab wann sie gültig sind.

Bei einem neuen Zähler sähe das so aus:
```
entryValueFactorList: {
  "": {
    gasConversionFactor: 0,
    gasCalorificValue: 0,
    entryValueFactor: 1
  }
}
```

Setzt der Nutzer einen ersten Wert, z.B. `gasCalorificValue = 10.1` und `gasConversionFactor = 0.9`, dann...
```
entryValueFactorList: {
  "": {
    gasConversionFactor: 0.9,
    gasCalorificValue: 10.1,
    entryValueFactor: 1
  }
}
```

Setzt der Nutzer einen Wert, ab wann der Faktor-Wert gilt, dann
```
entryValueFactorList: {
  "2023-10-29T21:53": {
    gasConversionFactor: 0.99,
    gasCalorificValue: 10.11,
    entryValueFactor: 1
  },
  "": {
    gasConversionFactor: 0.9,
    gasCalorificValue: 10.1,
    entryValueFactor: 1
  }
}
```

Wenn dieser Zeitpunkt nach der ersten Ablesung liegt, dann soll bis dahin trotzdem dieser Wert verwendet werden.

## Bedienung

Es muss dafür eine Möglichkeit geschaffen werden, Werte für Zeiträume einzutragen.

Vorschlag von Flo:

![Image](https://github.com/ehwplus/app-backlog/assets/13302336/8300ce3f-ce61-4115-8c4d-ad8fd29f199e)

![Image](https://github.com/ehwplus/app-backlog/assets/13302336/1c00df3f-7cbf-4825-99bb-e7d5cc08fa45)

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1194

**Comment by janine0407** [comment]
> Wehre es nicht etwas einfacher wenn man den Brennwert und die Zustandszahl gleich mit, bei den einzelnen Verträgen mit unter bringt? Die Werte als Standard wo sie jetzt vorhanden sind, sollte in den Verträgen ein Wert eingetragen sein diese eben vorrangig benutzen. 

https://support.ehwplus.com/#ticket/zoom/1161

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1265

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/278


> Mein Vorschlag: Zu jedem angelegten Vertrag sollte die Zustandszahl und der Brennwert angegeben werden und nicht wie bisher nur einmalig für den Gaszähler

https://support.ehwplus.com/#ticket/zoom/1852

> Bessere Lösung: wie ich schon mal vorgeschlagen habe, sollten Sie die Werte Brennwert und Zustandszahl nicht beim Gaszähler sondern beim Gasvertrag integrieren.> 
> 
> Denn den Verbrauchspreis pro kwh , der sich ja auch ändert, wird ja auch beim Vertrag und nicht beim Gaszähler hinterlegt.
> 
> Resultat: gaspreis und Brennwert sind Angaben, die sich aus dem Vertrag ergeben und somit sollten Sie auch dort hinterlegt werden und nicht beim GasZähler

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/1936

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2162

**Comment by Ruudini** [comment]
Die Informationen zu den jeweiligen Werten sind erst mit der Gas Abrechnung verfügbar. Also nachträglich zum Eintragen der Zählerstände. 
Wenn ich mir die Komplexität oben anschaue und die aktuellen Möglichkeiten in der App, komme ich - obwohl ich mir ein mitführen bei den Zählerständen wünschen würde - zum Schluss:
Die Werte gehören in den Vertrag. Eine Aktualisierung des Vertrages ist mit jeder Abrechnung möglich. Die Werte können pro Abrechnung als Durchschnittswerte ermittelt werden und eingepflegt werden. 
Eigentlich ist es das gleiche, wie eine Preisanpassung. Nur nachträglich. Für die Prognose der Kosten genügen die letzten Durchschnittswert. 
Das lässt sich auch sachlich begründen: der Zähler misst nur die m3, nicht die kWh. Abgerechnet werden kWh, berechnet aus dem Zählerwert. Das so in der App abzubilden, wäre sogar ein Fortschritt zu den anderen Erfassungssystemen, die ich parallel nutze.

**Comment by timobaehr** [comment]
> Die Spezifikationen des gelieferten Gases schwanken zum Teil erheblich. Es wäre gut, das mit der Jahresrechnung auszugleichen, in dem man die tatsätlich abgerechneten m3 Gas und die tatsächlich abgerechneten kWh erfasst und damit den Jahresverbrauch hinsichtlich der Gasspezifikationen korrigieren könnte. für die laufenden Erfassungen sollten dann die durchschnittswerde des letzten Jahres eingestellt werden. So hat man eine realistische Einschätzung. Allerdings bedürfte es hier einer jährlichen Separierung im Datensatz - oder einer Kopplung an die Abrechnungsperiode.

https://support.ehwplus.com/#ticket/zoom/2400

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2574

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2742

**Comment by timobaehr** [comment]
`1.14.0`
