### ISSUE TITLE
kWh bei Aktivitäten werden auf-/abgerundet

### ISSUE THREAD

**Issue by janine0407** [ehwplus/app-backlog#95]
In der Übersicht der Aktivitäten werden manuell eingetragene kWh (Stromverbrauch nur für Aktivität wird gemessen) nicht mit Kommastellen angezeigt sondern auf volle kWh auf-/abgerundet. 
Für eine Vergleichbarkeit sollten in der Übersicht die kWh, wie bei der Eingabe, auch mit Kommastellen angezeigt werden.

**Comment by janine0407** [comment]
https://support.ehwplus.com/#ticket/zoom/1294

**Comment by timobaehr** [comment]
![Image](https://user-images.githubusercontent.com/13302336/236687948-3354f6a1-964e-473b-a0e8-c033e71733a1.png)
