### ISSUE TITLE
JSON-Datei in Geräte-Ordner speichern

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#96]
Als Nutzer kann ich aktuell die JSON-Datei teilen oder mit Google Drive synchronisieren. Zusätzlich möchte ich die Datei auch in einem lokalen App-Ordner speichern können. Die App soll dafür die Lese- und Schreibberechtigung für den Speicherzugriff abfragen.

**Comment by janine0407** [comment]
> Daher fände ich es sehr nützlich, wenn man sagen könnte nutze entweder Google Drive für den Sync oder einen lokalen Ordner X, der dann z.B. im Boxcryptor Volume liegt.

https://support.ehwplus.com/#ticket/zoom/181
